feat/landing-1
atls-academy/oksssvv.github.io pull request #11
Opened 2023-04-11 18:46 UTC by oksssvv

2023-04-12 22:08 UTC, TorinAsakura requested changes
убери .next в gitignore, кэш/билд директорий не должно быть в репе, кроме .yarn

2023-04-18 13:42 UTC, eshevlyakova commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +    <GlobalStyles />
Где ты видела в примерах чтобы так стили импортировались?

2023-04-18 13:42 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
> +  <Box width={['none', 1166]}>
Почему 2 брекпоинта? А для планшетов?

2023-04-18 13:42 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          Обучаем профессионалов
Смотри где пишется текст в наших проектах и как он в проект вставляется

2023-04-18 13:42 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          color='white'
Это все пишется в ui/theme. Перепиши везде

2023-04-18 13:42 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
Если вынесла в папке компонента какую-то часть кода, то правильно оформляй ее. Смотри в примеры => фрагменты

2023-04-18 13:42 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          <Button shape='formPaddingRounding' appearance='formBackgroundGhost'>
Исправь атрибуты для Button

2023-04-18 13:42 UTC, eshevlyakova commented on ui/button/src/button.interfaces.ts
> +  valueHeight?: object
Зачем тебе все эти пропс. Смотри какие есть в репозитории uikit в папке ui-proto (в этой папке можно увидеть как тот или иной компонент должен инициализироваться на проекте)

2023-04-18 15:41 UTC, oksssvv commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          <Button shape='formPaddingRounding' appearance='formBackgroundGhost'>
@eshevlyakova 

>Исправь атрибуты для Button

не совсем поняла, что конкретно ты имеешь ввиду?
название атрибута, или название свойства не верно составлено?

2023-04-18 15:49 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          <Button shape='formPaddingRounding' appearance='formBackgroundGhost'>
@oksssvv 
 разберись сначала с этим https://github.com/atls-academy/oksssvv.github.io/pull/11#discussion_r1170060366, тогда это само собой решится

2023-04-18 15:55 UTC, oksssvv commented on landing/fragments/landing-hero/src/lead-component.tsx
> +  <Box width={['none', 1166]}>
@eshevlyakova 

на что ориентироваться при создании версии для планшета?
в макете десктоп и мобайл, брать средние размеры?

2023-04-18 15:56 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/lead-component.tsx
> +  <Box width={['none', 1166]}>
> Почему 2 брекпоинта? А для планшетов?

Потому что планшетная версия не предусмотрена дизайном, она тут не нужна, до 85% таблетов используют разрешение десктопа.

2023-04-18 15:56 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/lead-component.tsx
> +  <Box width={['none', 1166]}>
> @eshevlyakova
> 
> на что ориентироваться при создании версии для планшета? в макете десктоп и мобайл, брать средние размеры?

Ни на что, иди дальше, таблет-версия не нужна

2023-04-19 09:47 UTC, oksssvv commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          Обучаем профессионалов
@eshevlyakova 

**Скоуп**
вставка текстовых кусков

**Описание**
нужно валидно разместить текстовую часть в проекте

**Воспроизведение**
1. создаю ru.json с необходимыми строками текста
2. оборачиваю рендерную страницу в <IntlProvider>
3. меняю обычный текст на <FormattedMessage> 
4. указываю айди и дефолтМесседж
(в общем все по примеру)
5. вижу ошибку на странице

**Логи**

`
1 of 1 unhandled error
Server Error
**Error: [React Intl] Could not find required 'intl' object. <IntlProvider> needs to exist in the component ancestry.**

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
invariant
../../../../../../.yarn/berry/cache/@formatjs-ecma402-abstract-npm-1.11.1-174e729a12-9.zip/node_modules/@formatjs/ecma402-abstract/utils.js (87:0)
invariantIntlContext
../../../../.yarn/__virtual__/react-intl-virtual-d379c72ac8/3/.yarn/berry/cache/react-intl-npm-5.24.3-c8cb0c2bf3-9.zip/node_modules/react-intl/src/utils.js (9:0)
useIntl
../../../../.yarn/__virtual__/react-intl-virtual-d379c72ac8/3/.yarn/berry/cache/react-intl-npm-5.24.3-c8cb0c2bf3-9.zip/node_modules/react-intl/src/components/useIntl.js (9:0)
FormattedMessage
../../../../.yarn/__virtual__/react-intl-virtual-d379c72ac8/3/.yarn/berry/cache/react-intl-npm-5.24.3-c8cb0c2bf3-9.zip/node_modules/react-intl/src/components/message.js (19:0)
renderWithHooks
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5661:16)
renderIndeterminateComponent
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5734:15)
renderElement
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5949:7)
renderMemo
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5871:3)
renderElement
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (6014:11)
renderNodeDestructiveImpl
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (6107:11)
`

**Вопрос**
По какой причине может появиться такая ошибка?

2023-04-19 09:50 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          Обучаем профессионалов
@oksssvv а где код? И отформатируй пожалуйста запрос

2023-04-19 10:46 UTC, oksssvv commented
@eshevlyakova

**Скоуп**
Валидное размещение текста

**Описание**
Необходимо соответствующе разместить текстовую часть в проекте

**Воспроизведение**
1. создаю файл `ru.json` с необходимыми строками текста
2. оборачиваю рендерную страницу в `IntlProvider`
3. меняю обычный текст на `FormattedMessage`
4. указываю `id` и `defaultMessage`
5. вижу ошибку при загрузке страницы

**Логи**

`
1 of 1 unhandled error
Server Error
Error: [React Intl] Could not find required 'intl' object. needs to exist in the component ancestry.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
invariant
../../../../../../.yarn/berry/cache/@formatjs-ecma402-abstract-npm-1.11.1-174e729a12-9.zip/node_modules/@formatjs/ecma402-abstract/utils.js (87:0)
invariantIntlContext
../../../../.yarn/virtual/react-intl-virtual-d379c72ac8/3/.yarn/berry/cache/react-intl-npm-5.24.3-c8cb0c2bf3-9.zip/node_modules/react-intl/src/utils.js (9:0)
useIntl
../../../../.yarn/virtual/react-intl-virtual-d379c72ac8/3/.yarn/berry/cache/react-intl-npm-5.24.3-c8cb0c2bf3-9.zip/node_modules/react-intl/src/components/useIntl.js (9:0)
FormattedMessage
../../../../.yarn/virtual/react-intl-virtual-d379c72ac8/3/.yarn/berry/cache/react-intl-npm-5.24.3-c8cb0c2bf3-9.zip/node_modules/react-intl/src/components/message.js (19:0)
renderWithHooks
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/virtual/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5661:16)
renderIndeterminateComponent
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/virtual/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5734:15)
renderElement
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/virtual/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5949:7)
renderMemo
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/virtual/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (5871:3)
renderElement
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/virtual/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (6014:11)
renderNodeDestructiveImpl
file:///home/oksssvv/Desktop/oksssvv.github.io/.yarn/virtual/react-dom-virtual-b061728be9/3/.yarn/berry/cache/react-dom-npm-18.2.0-dd675bca1c-9.zip/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js (6107:11)
`

**Вопрос**
По какой причине может появиться такая ошибка?

2023-04-19 10:49 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/lead-component.tsx
> +          Обучаем профессионалов
@oksssvv @eshevlyakova файлы с переводами создаются в процессе сборки приложения, а не руками

2023-04-19 12:35 UTC, eshevlyakova commented
@oksssvv 

> По какой причине может появиться такая ошибка?

Это происходит потому что  у компонента, который использует `FormattedMessage`, неправильно заданы зависимости (можешь почитать про [peerDependencies](https://github.com/atls/uikit/wiki/Что-такое-peerDependencies))

2023-04-19 14:37 UTC, oksssvv commented on landing/fragments/landing-hero/src/lead-component.tsx
@eshevlyakova 

>Если вынесла в папке компонента какую-то часть кода, то правильно оформляй ее

ты имеешь ввиду компонент lead сделать фрагментом?

или во фрагменте landing-hero сделать для него отдельную папку (назвать content например) с собственным index.ts и component.tsx

2023-04-19 14:39 UTC, oksssvv commented on landing/fragments/landing-hero/src/lead-component.tsx
Андрей сказал что СоцЛинки не являются фрагментом, я подумала что заголовок и дескриптор (lead) тоже

2023-04-19 15:01 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/lead-component.tsx
@oksssvv 

> или во фрагменте landing-hero сделать для него отдельную папку (назвать content например) с собственным index.ts и component.tsx

Верно

2023-04-20 04:22 UTC, eshevlyakova reviewed
И что за [файл yarn](https://github.com/atls-academy/oksssvv.github.io/blob/feat/landing-1/yarn) в корне проекта?

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +  <Box width={['100%']} backgroundColor='#616161' flexDirection={['column']} margin={['none']}>
Если значение только одно на всех разрешениях, то достаточно написать только в скобках (без скобок)

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +      <Box width={['100%']} flexDirection={['column', 'row']} backgroundColor='#616161'>
Цвета из ui/theme берутся

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/content/content.lead.tsx
Правильно оформи компоненты (в одной папке один компонент и index.ts в котором он экспортируется) и назови файлы по кодстайлу

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/content/content.lead.tsx
> +          color='white'
Здесь тоже исправь цвета

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/content/content.lead.tsx
> +        <Column flexBasis={['100%', 640]} flexShrink={[0]}>
У тебя внутри Column есть контент, значит это не просто блок для задания отступа, следовательно лучше использовать стандартные width/height

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/content/content.lead.tsx
> +        <Layout flexBasis={[448]} />
Если значение одно, достаточно использовать только фигурные скобки

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/content/content.social-link.tsx
> +          </Link>
Оберни Link в Box, а внутри Box убери. Это даже с точки зрения семантики не корректно: у тебя внутри ссылки div элемент

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
Переименуй файл по кодстайлу

2023-04-20 04:22 UTC, eshevlyakova commented on landing/fragments/landing-navigation/src/landing-navigation.component.tsx
Переименуй файл по кодстайлу

2023-04-20 04:22 UTC, eshevlyakova commented on ui/button/src/button.styles.ts
Посмотри как в других проектах пишутся стили для кнопок (они должны автоматически создаваться при запуске команды из package.json)

2023-04-20 04:22 UTC, eshevlyakova commented on ui/logo/src/logo.component.tsx
> +const Logo = () => (
Логотип это ссылка, опять же посмотри в примерах

2023-04-20 04:22 UTC, eshevlyakova commented on ui/text/src/text.component.tsx
Для чего нужен этот файл и откуда ты его взяла?

2023-04-20 04:22 UTC, eshevlyakova commented on ui/theme/src/global.styles.tsx
> +        }
Ты где-то css анимацию и капчу используешь?

2023-04-20 04:22 UTC, eshevlyakova commented on ui/theme/src/theme/backgrounds.ts
> +  gray: '#616161',
Только rgb/rgba формат

2023-04-20 04:22 UTC, eshevlyakova commented on ui/theme/src/theme/colors.ts
> +    gray: '#616161',
Только rgb/rgba формат

2023-04-20 04:22 UTC, eshevlyakova commented on ui/theme/src/theme/fonts.ts
> +  main: 'Helvetica',
Посмотри как называются шрифты

2023-04-22 09:21 UTC, eshevlyakova commented on landing/entrypoints/renderer/locales/ru.json
> +  "landing_hero_lead.we_dont_teach_programming": "Мы не учим программированию и дизайну, мы учим мышлению способному релизовывывать невозможные идеи."
Переименуй по код стайлу (в примерах посмотри как формируются названия)

2023-04-22 09:21 UTC, eshevlyakova commented on landing/fragments/landing-hero/package.json
> +    "react-intl": "^6.1.2"
react-intl это dev зависимость, убери ее отсюда

2023-04-22 09:21 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/hero.component.tsx
> +    <Row width='100%'>
У компонента Row, [по умолчанию](https://github.com/atls/hyperion/blob/master/ui-parts/layout/src/row/row.component.ts#L12) ширина 100%

2023-04-22 09:21 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +      <Row flexWrap='wrap'>
Зачем тебе это свойство? Если у тебя только один компонент внутри

2023-04-22 09:21 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +  <Box width='100%' justifyContent='center'>
Можешь использовать Row и не задавать 100% ширины

2023-04-22 09:21 UTC, eshevlyakova commented on landing/pages/index-page/package.json
> +    "react-intl": "^6.1.2"
У тебя в этом компоненте нет текста, поэтому эта зависимость не нужна

2023-04-22 09:21 UTC, eshevlyakova commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +      <Box width='100%'>
Также используй Row

2023-04-22 09:21 UTC, eshevlyakova commented on landing/fragments/landing-navigation/package.json
> +    "react-intl": "^6.1.2",
У тебя в этом компоненте нет текста, поэтому этот пакет тут не нужен

2023-04-22 09:21 UTC, eshevlyakova commented on ui/button/src/button.component.tsx
Сделай структуры всех файлов в ui/button как [тут](https://github.com/torin-asakura/drum-in/tree/master/ui/button)

2023-04-22 09:21 UTC, eshevlyakova commented on ui/theme/src/theme/backgrounds.ts
Для чего тебе этот файл?

2023-04-22 15:57 UTC, oksssvv commented on ui/button/src/button.component.tsx
@eshevlyakova 

т.е. генератор автоматически сгенерит апперанс стили? 

в файле button.generator.ts выдает ошибку, потому что в в ui/theme не указываются состояния кнопок - default, pressed, hover, disabled

я не указывала состояния, т.к. в макете их нет, там чисто дефолт кнопки без обвесов

2023-04-22 15:59 UTC, eshevlyakova commented on ui/button/src/button.component.tsx
> в макете их нет, там чисто дефолт кнопки без обвесов

В макете есть состояния кнопок, вкладка компоненты

2023-04-22 16:03 UTC, oksssvv commented on ui/button/src/button.component.tsx
@eshevlyakova 

понял, просто я увидела что состояния появились в третьем степе лендинга, и подумала что на первом этапе они не делаются

2023-04-22 16:03 UTC, oksssvv commented on ui/button/src/button.component.tsx
> @eshevlyakova
> 
> понял, просто я увидела что состояния появились в третьем степе лендинга (в info), и подумала что на первом этапе они не делаются

2023-04-22 16:04 UTC, eshevlyakova commented on ui/button/src/button.component.tsx
> понял, просто я увидела что состояния появились в третьем степе лендинга, и подумала что на первом этапе они не делаются

Тогда можешь указать один цвет для всех состояний, а на третьем этапе делать как показано

2023-04-24 03:32 UTC, eshevlyakova commented on landing/entrypoints/renderer/locales/ru.json
> +  "about_us.we_dont_teach_programming": "Мы не учим программированию и дизайну, мы учим мышлению способному релизовывывать невозможные идеи."
Неправильно. name_fragment.text_translated

2023-04-24 03:32 UTC, eshevlyakova commented on ui/button/src/button.component.tsx
> +          valueBackground={props.valueBackground}
Ты в кнопке используешь иконку? Убери это

2023-04-24 03:32 UTC, eshevlyakova commented on ui/button/src/button.interfaces.ts
> +  horizontalLocation?: 'left' | 'right'
Лишние пропс

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/hero.component.tsx
> +    </Column>
Лишняя обертка, у тебя и так для родителя задан column, зачем ты еще раз оборачиваешь в Column?

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/hero.component.tsx
> +    <Row>
Лишняя вложенность (Row)

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +            fontFamily='primary'
Для чего ты текст в Column оборачиваешь?

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +            <Button size='bigPaddingMediumHeight' variant='transparentBorder'>
Вместо использования еще одного Column, ты же можешь задать выравнивание для родителя flex элементов

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +        <Box flexDirection={['row', 'column']} width='100%' justifyContent='space-between'>
Странная вложенность Box => Column => Box с flex-direction=column
Проверь какие компоненты у тебя ничего не дают, или какие можно убрать, добавив их свойства в другие

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +    <Row>
Лишняя вложенность, у тебя Row, дает только одну ширину, тогда лучше указать ее для Box

2023-04-24 03:32 UTC, eshevlyakova commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +        <Box width='100%'>
Используй Row (и исправь этот момент в другом фрагменте тоже)

2023-04-24 07:29 UTC, oksssvv commented on ui/button/src/button.interfaces.ts
> +  horizontalLocation?: 'left' | 'right'
@eshevlyakova 
Хорошо, подчищу, просто не стала трогать на всякий

2023-04-24 17:45 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +              defaultMessage='Мы не учим программированию и дизайну, мы учим мышлению, способному реализовывывать невозможные идеи.'
опечатка, если она из дизайна - надо оставить комментарий в фигме, но, что-то сомнительно

2023-04-24 17:55 UTC, TorinAsakura requested changes

2023-04-24 17:55 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +      <Row justifyContent='space-between'>
зачем тебе тут джастифай? у тебя есть чёткие отступы в дизайне

2023-04-24 17:55 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +    <Box flexDirection={['row', 'column']} width='100%' justifyContent='space-between'>
аналогично

2023-04-24 19:37 UTC, oxiqod commented
@eshevlyakova 

**Скоуп**
запуск билд скрипта 

**Описание**
файл ru.json должен создаваться в процессе сборки приложения

**Воспроизведение**
1. запускаю `yarn workspace @landing/renderer-entrypoint run build --no-lint`
2. вижу ошибку

**Контекст**
[строка кода в которой указывается ошибка](https://github.com/atls-academy/oksssvv.github.io/pull/11/commits/502bb0490bec49ed78d53037533f849e4d9c3aad#file-landing-entrypoints-renderer-src-pages-_app-tsx-L9)

**логи при наведении на свойство messages в IntlProvider**
`
TS2769: No overload matches this call.   Overload 1 of 2, '(props: PropsWithChildren<IntlConfig> | Readonly<PropsWithChildren<IntlConfig>>): IntlProvider', gave the following error.     Type '{}' is not assignable to type 'Record<string, string> | Record<string, MessageFormatElement[]>'.       Type '{}' is not assignable to type 'Record<string, MessageFormatElement[]>'.         Index signature for type 'string' is missing in type '{}'.   Overload 2 of 2, '(props: PropsWithChildren<IntlConfig>, context: any): IntlProvider', gave the following error.     Type '{}' is not assignable to type 'Record<string, string> | Record<string, MessageFormatElement[]>'.       Type '{}' is not assignable to type 'Record<string, MessageFormatElement[]>'.  types.d.ts(34, 5): The expected type comes from property 'messages' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<IntlProvider> & Pick<Readonly<PropsWithChildren<IntlConfig>> & Readonly<...>, "wrapRichTextChunksInFragment" | ... 2 more ... | "children"> & Partial<...> & Partial<...>' types.d.ts(34, 5): The expected type comes from property 'messages' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<IntlProvider> & Pick<Readonly<PropsWithChildren<IntlConfig>> & Readonly<...>, "wrapRichTextChunksInFragment" | ... 2 more ... | "children"> & Partial<...> & Partial<...>'
`

**Логи ошибки при запуске билда**

`
warn  - Linting is disabled
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

../locales/ru.json
Module parse failed: Unexpected end of JSON input while parsing near ''
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
SyntaxError: Unexpected end of JSON input while parsing near ''
    at JSON.parse (<anonymous>)
    at parseJson (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:15303:17)
    at JsonParser.parse (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:95552:7)
    at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49543:26
    at processResult (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49256:11)
    at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49316:5
    at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:139505:3
    at iterateNormalLoaders (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:139331:10)
    at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:139322:4
    at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/__virtual__/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49290:15

Import trace for requested module:
./pages/_app.tsx

 Build failed because of webpack errors
`

**Вопрос**
Почему возникает данная ошибка?

2023-04-25 09:56 UTC, TorinAsakura commented
> @eshevlyakova
> 
> **Скоуп** запуск билд скрипта
> 
> **Описание** файл ru.json должен создаваться в процессе сборки приложения
> 
> **Воспроизведение**
> 
> 1. запускаю `yarn workspace @landing/renderer-entrypoint run build --no-lint`
> 2. вижу ошибку
> 
> **Контекст** [строка кода в которой указывается ошибка](https://github.com/atls-academy/oksssvv.github.io/pull/11/commits/502bb0490bec49ed78d53037533f849e4d9c3aad#file-landing-entrypoints-renderer-src-pages-_app-tsx-L9)
> 
> **логи при наведении на свойство messages в IntlProvider** `TS2769: No overload matches this call.   Overload 1 of 2, '(props: PropsWithChildren<IntlConfig> | Readonly<PropsWithChildren<IntlConfig>>): IntlProvider', gave the following error.     Type '{}' is not assignable to type 'Record<string, string> | Record<string, MessageFormatElement[]>'.       Type '{}' is not assignable to type 'Record<string, MessageFormatElement[]>'.         Index signature for type 'string' is missing in type '{}'.   Overload 2 of 2, '(props: PropsWithChildren<IntlConfig>, context: any): IntlProvider', gave the following error.     Type '{}' is not assignable to type 'Record<string, string> | Record<string, MessageFormatElement[]>'.       Type '{}' is not assignable to type 'Record<string, MessageFormatElement[]>'. types.d.ts(34, 5): The expected type comes from property 'messages' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<IntlProvider> & Pick<Readonly<PropsWithChildren<IntlConfig>> & Readonly<...>, "wrapRichTextChunksInFragment" | ... 2 more ... | "children"> & Partial<...> & Partial<...>' types.d.ts(34, 5): The expected type comes from property 'messages' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<IntlProvider> & Pick<Readonly<PropsWithChildren<IntlConfig>> & Readonly<...>, "wrapRichTextChunksInFragment" | ... 2 more ... | "children"> & Partial<...> & Partial<...>'`
> 
> **Логи ошибки при запуске билда**
> 
> ` warn - Linting is disabled warn - You have enabled experimental feature(s). warn - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
> 
> info - Checking validity of types info - Creating an optimized production build Failed to compile.
> 
> ../locales/ru.json Module parse failed: Unexpected end of JSON input while parsing near '' You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders SyntaxError: Unexpected end of JSON input while parsing near '' at JSON.parse () at parseJson (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:15303:17) at JsonParser.parse (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:95552:7) at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49543:26 at processResult (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49256:11) at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49316:5 at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:139505:3 at iterateNormalLoaders (/home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:139331:10) at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:139322:4 at /home/oksssvv/Desktop/oksssvv.github.io/.yarn/**virtual**/next-virtual-daf36fb0ce/3/.yarn/berry/cache/next-npm-12.1.0-7f99f50e0f-9.zip/node_modules/next/dist/compiled/webpack/bundle5.js:49290:15
> 
> Import trace for requested module: ./pages/_app.tsx
> 
> Build failed because of webpack errors `
> 
> **Вопрос** Почему возникает данная ошибка?

у тебя нет рабочего окружения для решения подобных задач, налицо:
- отсутствует next.config
- нет зависимостей для работы окружения из наших пакетов @atls

В качестве примера можно взять любую репу коих у вас под носом пяток. Можно посмотреть шинный двор, дрим тим.

2023-04-26 12:31 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +        </Text>
Текстовые компоненты нужно во что-то оборачивать, по дефолту можно использовать Box

2023-04-26 12:31 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +  <Row justifyContent='center' width={[335, 56]} height={[44, 200]}>
Для чего тебе justifyContent если у тебя внутри только один элемент?

2023-04-26 13:04 UTC, eshevlyakova approved these changes

2023-04-27 15:38 UTC, TorinAsakura requested changes

2023-04-27 15:38 UTC, TorinAsakura commented on landing/entrypoints/renderer/package.json
> +    "typescript": "^4.3.5"
У тебя что-то с зависимостями, во-первых какие-то древние версии, откуда ты их вообще взяла? Во-вторых - почему у тебя тайпскрипт в локальном пакете, а не в корневом? Что, react-helmet нужен для работы приложения? Точно не dev должно лежать?

2023-04-27 15:38 UTC, TorinAsakura commented on landing/entrypoints/renderer/package.json
> +    "start": "node dist/index.js"
Полагаю, прежде чем отправить на ревью тестирование через build & start проводилось?

2023-04-27 15:38 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      <Box display={['none', 'flex']}>
что за каскад дивов?

2023-04-27 15:38 UTC, TorinAsakura commented on package.json
> +    "auth",
маска где?

2023-04-27 15:38 UTC, TorinAsakura commented on package.json
> +    "react-intl": "5.24.3",
зачем резолюшены?

2023-04-27 15:38 UTC, TorinAsakura commented on package.json
> +    "react-intl": "5.24.3",
почему нода 16-я когда мы уже давно на 18-й?

2023-04-27 15:38 UTC, TorinAsakura commented on ui/condition/src/condition.component.tsx
> +  if (smooth) {
а где у тебя тут smooth и зачем тебе тут понадобился фреймер?

2023-04-27 15:38 UTC, TorinAsakura commented on ui/utils/src/hooks/use-popover.hook.ts
> +  const { layerProps, triggerProps, renderLayer } = useLayer({
а где у тебя тут используется поповер?

2023-05-06 13:12 UTC, oksssvv commented
@eshevlyakova 

**Скоуп**
запуск билд скрипта

**Описание**
после нескольких запусков скрипта команда yarn check начала выбрасывать кучу ошибок, я так понимаю дело в чем то одном.
Скрипты в проекте работают, запускается dev, build и start (рендер выглядит как должен, все на месте)

**Воспроизведение**
1. запускаю  yarn check
2. на проверке TypeCheck - выкидывается огромное кол-во ошибок

**Часть логов ошибок**
`
Erro: Subsequent property declarations must have the same type.  Property 'datalist' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLDataListElement>, HTMLDataListElement>', but here 
➤ YN0000: │       has type 'DetailedHTMLProps<HTMLAttributes<HTMLDataListElement>, HTMLDataListElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'dd' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'del' must be of type 'DetailedHTMLProps<DelHTMLAttributes<HTMLModElement>, HTMLModElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<DelHTMLAttributes<HTMLModElement>, HTMLModElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Erro: Subsequent property declarations must have the same type.  Property 'details' must be of type 'DetailedHTMLProps<DetailsHTMLAttributes<HTMLDetailsElement>, HTMLDetailsElement>', but 
➤ YN0000: │       here has type 'DetailedHTMLProps<DetailsHTMLAttributes<HTMLDetailsElement>, HTMLDetailsElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'dfn' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Erro: Subsequent property declarations must have the same type.  Property 'dialog' must be of type 'DetailedHTMLProps<DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>', but here 
➤ YN0000: │       has type 'DetailedHTMLProps<DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'div' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'dl' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLDListElement>, HTMLDListElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<HTMLAttributes<HTMLDListElement>, HTMLDListElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'dt' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ ../../.yarn/berry/cache/@types-react-npm-18.2.5-839030c683-9.zip/node_modules/@types/react/ts5.0/index.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Subsequent property declarations must have the same type.  Property 'em' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 
➤ YN0000: │        'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
`

**Вопрос**
Из-за чего может быть этот сбой? и как его пофиксить

2023-05-06 17:09 UTC, eshevlyakova commented on landing/entrypoints/renderer/package.json
> +    "typescript": "^4.6.2"
Обнови версию тайпскрипта

2023-05-06 17:09 UTC, eshevlyakova commented on landing/entrypoints/renderer/package.json
> +    "@types/styled-system": "^5.1.16",
Проверь, тут есть неиспользованные пакеты типов

2023-05-06 18:58 UTC, oksssvv commented on landing/entrypoints/renderer/package.json
> +    "typescript": "^4.6.2"
@eshevlyakova 
Я как в корневом ставила, могу последнюю указать?

2023-05-07 12:14 UTC, TorinAsakura approved these changes

2023-05-07 13:44 UTC, merged