feat/landing 2
atls-academy/oksssvv.github.io pull request #14
Opened 2023-04-28 16:33 UTC by oksssvv

2023-05-08 13:04 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
Почему у тебя Box обернут в Box?

2023-05-08 13:04 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
Аналогично

2023-05-08 13:04 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            display={['none', 'inline']}
Не нужно задавать display компоненту Text. Задавай блочному элементу

2023-05-08 14:22 UTC, oksssvv commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
@eshevlyakova 
ImageBlock не дает задать изображению нужный размер, поэтому поместила в Box
есть другой вариант как можно реализовать?

2023-05-08 14:27 UTC, TorinAsakura commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
> @eshevlyakova
> ImageBlock не дает задать изображению нужный размер, поэтому поместила в Box
> есть другой вариант как можно реализовать?

Неверно. Ты не задала главный вопрос "почему imageBlock не даёт задать изображению нужный размер?", а просто хернула его в Бокс, опять.

2023-05-08 14:30 UTC, oxiqod commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
@TorinAsakura 
почему imageBlock не даёт задать изображению нужный размер?

2023-05-08 14:31 UTC, TorinAsakura commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
> @TorinAsakura
> почему imageBlock не даёт задать изображению нужный размер?

Да не мне же! Себе его задай и продебаж! Может мне ещё и код за тебя написать?

2023-05-09 07:29 UTC, oksssvv commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
@eshevlyakova 
в ImageBlock по дефолту можно менять ширину и высоту?
я попыталась делать как в других компонентах - 2 значения для мобильной версии и десктопной, компонент на это никак не реагирует, хотя зависимости расставлены правильно, все проверила

2023-05-09 10:20 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            <Box width={['28px', '40px']} height={['28px', '40px']}>
@oksssvv 

> в ImageBlock по дефолту можно менять ширину и высоту?

Этот компонент образован от стандартного [img](https://github.com/atls/hyperion/blob/master/ui-parts/image/src/image-block/image-block.component.tsx#L5), у которого в атрибутах есть ширина и высота => да

2023-05-11 06:15 UTC, oksssvv commented on landing/fragments/landing-info/src/info.component.tsx
> +            display={['none', 'inline']}
@eshevlyakova 
в примерах компоненту `text` не раз задается атрибут `display`, или ты именно об этом примере, где текст отключается?
`display={['none', 'inline']}`

2023-05-11 06:18 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            display={['none', 'inline']}
@oksssvv 
> или ты именно об этом примере, где текст отключается?

Да

2023-05-11 09:50 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +  <Column width={['none', 1166]}>
Для свойства width не значения none

2023-05-11 09:50 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +              defaultMessage=' становится всё более многолюдным, востребованность по направлениям при этом не снижается '
Не делай отступы в самом сообщении, для этого есть `<Space />` в ui/text

2023-05-11 09:50 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            verticalAlign='sub'
Зачем тебе свойство verticalAlign, если выше ты используешь alignItems?

2023-05-11 09:50 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            <FormattedMessage id='landing_info.' defaultMessage=' Но, ' />
Некорректный id

2023-05-11 12:37 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            </Box>
Копипаст кода, ты можешь задать для ImageBlock значения 100%, и корректировать ширину `<Box>` (width={[28,40]})

2023-05-11 12:37 UTC, eshevlyakova commented on landing/pages/index-page/src/index.page.tsx
> +    gradient='bgPage'
Некорректное название фона, а если у тебя несколько страниц?

2023-05-11 12:37 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +          fontFamily='primary'
Шрифт primary (то есть основной) по умолчанию применяется

2023-05-11 12:37 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +              color='text.primary'
Если ты уже задала для родителя эти свойства они будут наследоваться, не нужно их повторять

2023-05-11 12:37 UTC, eshevlyakova commented on landing/fragments/landing-hero/src/about-us/about-us.component.tsx
> +      </Text>
Строчный элемент не обернут

2023-05-11 13:11 UTC, oxiqod commented on landing/fragments/landing-info/src/info.component.tsx
> +            </Box>
@eshevlyakova 
т.е. сделать отдельный Box для ImageBlock, для того, что-бы корректировать размер картинки изменяя размер бокса?

2023-05-11 13:14 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            </Box>
> сделать отдельный Box для ImageBlock, для того, что-бы корректировать размер картинки изменяя размер бокса?

Да, в этом случае вложенность будет Box>Box>Image , но первый блок это контейнер со своими размерами и фоном, а второй для размера изображений на разных разрешениях

2023-05-12 03:41 UTC, eshevlyakova requested changes
И у последних двух коммитов некорректные названия. Первый - почему ты используешь chore, если исправляешь код (fix). chore можно использовать к примеру для обновления yarn или других зависимостей
А второй - почему test? если ты там добавляешь отступ, то есть опять fix

2023-05-12 03:41 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +              width={['52px', '76px']}
Ты смотрела через консоль у тебя блоки с картинкой точно не сжимает по ширине? Если да, то используй flexShrink=0

2023-05-12 03:41 UTC, eshevlyakova commented on landing/pages/index-page/src/index.page.tsx
> +    gradient='bgHeroInfo'
Вопрос тот же: если у тебя несколько страниц, то на них будет разный hero. Называй фон не на основе того где он используется, а на основе того какой он (цвет, градиент)

2023-05-12 03:41 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            lineHeight='medium'
А почему ты не задаешь color для Text?

2023-05-12 11:46 UTC, oksssvv commented on landing/fragments/landing-info/src/info.component.tsx
> +            lineHeight='medium'
@eshevlyakova 
Подумала, что тут как в случае с FonrFamily, необходимый цвет текста записан как primary и на рендере корректно отражается

**Медиа**
![Снимок экрана от 2023-05-12 14-44-17](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/cda9f144-148a-4e37-9a88-bf529f36f844)

2023-05-12 11:53 UTC, oxiqod commented on landing/fragments/landing-info/src/info.component.tsx
> +              width={['52px', '76px']}
@eshevlyakova 
ничего не сжимает, у них только 2 размера при любом экране - десктоп 76x52 или мобайл 52x36,

2023-05-12 11:59 UTC, eshevlyakova commented on landing/fragments/landing-info/src/info.component.tsx
> +            lineHeight='medium'
@oksssvv 

> Подумала, что тут как в случае с FontFamily, необходимый цвет текста записан как primary и на рендере корректно отражается

Цветов на сайте достаточно много, но насколько я знаю с FontFamily во всех примерах есть primary, а цвет называется в зависимости от самого цвета, а не частоте его использования на сайте

2023-05-12 12:14 UTC, eshevlyakova approved these changes

2023-05-17 14:24 UTC, TorinAsakura approved these changes

2023-05-17 14:24 UTC, merged