feat/landing-4
atls-academy/oksssvv.github.io pull request #18
Opened 2023-05-19 14:47 UTC by oksssvv

2023-05-19 16:36 UTC, TorinAsakura requested changes

2023-05-19 16:36 UTC, TorinAsakura commented on landing/fragments/landing-process/src/items/items.component.tsx
> +  <Box>
вот опять - зачем?

2023-05-19 16:36 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +        <Box display={['none', 'flex']} width={1166} alignItems='end'>
а если ширина будет отличаться от той, что ты указала? Что тогда?

2023-05-19 16:48 UTC, oksssvv commented on landing/fragments/landing-process/src/items/items.component.tsx
> +  <Box>
@TorinAsakura  
1й бокс действует как контейнер для одного элемента `item`, на рендере в нем горизонтально расположены 3 элемента ( номер, заголовок, описание)
2й бокс это обертка для создания внешнего вида нумерования пункта

(если убрать первый бокс- вертка валится, потому что уже не дисплей: флекс)

2023-05-19 18:10 UTC, TorinAsakura commented on landing/fragments/landing-process/src/items/items.component.tsx
> +  <Box>
Чтож, если там вертикальное направление, полагаю, это должен быть не бокс…да?

2023-05-23 06:47 UTC, oksssvv commented
@TorinAsakura 

**Скоуп**
добавление слайдера

**Описание**
нужно добавить слайдер в фрагмент `courses`

**Воспроизведение**
1. смотрю примеры и по аналогии добавляю в ui новый компонент 
2. создаю пакедж  `@ui/slider` и ставлю зависимости
3. запускаю yarn, получаю ответ в поле `Link step` - `swiper@npm:8.3.1 must be built because it never has been before or the last one failed`
4. запускаю yarn check - получаю ошибку Typecheck - 
`.yarn/unplugged/swiper-npm-8.3.1-7575c41fae/node_modules/swiper/react/swiper-react.d.ts`
`Error: Cannot find module 'react' or its corresponding type declarations.`

**Вопрос**
Из-за чего эта ошибка?

2023-05-23 08:29 UTC, TorinAsakura commented
@oksssvv 3. Это нормальный процесс линковки, почитай уже про работу зависимостей во втором ярне
4. Ошибка тебе явно говорит откуда она растёт, у тебя в корне свайпер анплагнут, в котором, не может найтись реакт. Не?

2023-05-24 07:47 UTC, oksssvv commented
@TorinAsakura 

**Скоуп**
Создание слайдера в мобильной версии

**Описание**
Был создан слайдер, рендер отрабатывает как надо и слайдер работает, но при проверке `type check` - выдает ошибку

**Воспроизведение**
1. создан `ui` компонент `Slider` (проверка молчит)
2. когда в фрагменте создаю импорт и расставляю компоненты `Swiper` и `SwiperSlide` - проверка проваливается

**Логи**
`
.yarn/unplugged/swiper-virtual-7cbc08c7b0/node_modules/swiper/react/swiper-react.d.ts
Erro: Interface 'SwiperProps' incorrectly extends interface 'Omit<HTMLAttributes<HTMLElement>, "onKeyPress" | "onProgress" | "onClick" | "onDoubleClick" | "onTouchEnd" | "onTouchMove" | 
"onTouchStart" | "onScroll" | "onTransitionEnd">'.
Types of property 'onResize' are incompatible.
Type '((swiper: Swiper) => void) | undefined' is not assignable to type 'ReactEventHandler<HTMLElement> | undefined'.
Type '(swiper: Swiper) => void' is not assignable to type 'ReactEventHandler<HTMLElement>'.
Types of parameters 'swiper' and 'event' are incompatible.
Type 'SyntheticEvent<HTMLElement, Event>' is missing the following properties from type 'Swiper': params, originalParams, $el, el, and 90 more.
`

`
.yarn/unplugged/swiper-virtual-7cbc08c7b0/node_modules/swiper/react/swiper-react.d.ts
Error: Interface 'SwiperSlideProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.
Types of property 'children' are incompatible.
Type 'ReactNode | ((slideData: SlideData) => ReactNode)' is not assignable to type 'ReactNode'.
Type '(slideData: SlideData) => ReactNode' is not assignable to type 'ReactNode'.
`

**Действия**
1. гуглила
2. пробовала менять различные завимости и версии в пакете ui и в компоненте который впоследствии рендерится
3. пробовала добавить некоторые зависимости в `.yarnrc.yml`


**Вопрос**
Почему может выбрасывать эту ошибку?

2023-05-24 08:22 UTC, TorinAsakura commented
@oksssvv Он написал почему: у тебя представленный тип не соответствует содержанию.

2023-05-24 10:13 UTC, TorinAsakura commented
@oksssvv https://github.com/nolimits4web/swiper/issues/5799

2023-05-24 18:54 UTC, TorinAsakura approved these changes

2023-05-24 18:54 UTC, merged