feat: landing-5
atls-academy/oksssvv.github.io pull request #20
Opened 2023-05-26 12:20 UTC by oksssvv

2023-05-26 23:08 UTC, TorinAsakura requested changes
У меня всё

![Снимок экрана 2023-05-27 в 02 07 01](https://github.com/atls-academy/oksssvv.github.io/assets/3940885/ab08e6ac-41dd-421c-b162-866a8b94fc4e)

а это вишенкой
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?

2023-05-26 23:08 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/line/line.component.tsx
> +  const infntLine = useMemo(
что это за наркоманский слэнг? т прнс?

2023-05-26 23:08 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/ticker.component.tsx
> +      <Line tech={'JavaScript,HTML,CSS,SASS,Vanilla JS,Jade'.split(',')} font='primary' />
серьёзно? в стринг запихала? может сразу из тхт?

2023-05-27 07:37 UTC, oksssvv commented on landing/fragments/landing-ticker/src/ticker.component.tsx
> +      <Line tech={'JavaScript,HTML,CSS,SASS,Vanilla JS,Jade'.split(',')} font='primary' />
@TorinAsakura 
имеешь ввиду нужно в react-init formatMessage?
я подумала если тут слова уже на англ. то можно оставить компонент Text

или ты имеешь ввиду массив нужен?

2023-05-27 07:37 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/ticker.component.tsx
> +      <Line tech={'JavaScript,HTML,CSS,SASS,Vanilla JS,Jade'.split(',')} font='primary' />
я имею ввиду, что это должен быть источник, а не хардкод

2023-05-27 15:06 UTC, TorinAsakura requested changes

2023-05-27 15:06 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/line/line.component.tsx
> +  const AnimBox = useMemo(
у тебя что? ограничение буфера на нейминги? что за Anim? Anima? Animathrone? Anime?

2023-05-27 15:06 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/line/line.component.tsx
> +  const techEl = useMemo(
Да что такое-то????

2023-05-27 15:06 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/technology/technology.component.tsx
> +  webDevelopment: 'JavaScript,HTML,CSS,SASS,Vanilla JS,Jade',
ты издеваешься? это должен быть массив объектов, по которому можно итерироваться, завтра нам надо будет выбросить хтмл, чо, пойдёшь в код, править строку? А если опечатаешься?

2023-05-27 15:06 UTC, TorinAsakura commented on ui/condition/src/condition.component.tsx
> +  },
анимацию выноси в отдельный слой some.animation.ts

2023-05-27 15:06 UTC, TorinAsakura commented on ui/condition/src/condition.component.tsx
> +  return null
зачем ты возвращаешь null?

2023-05-27 21:24 UTC, TorinAsakura requested changes
И я не увидел фиксов по неймингам

![Снимок экрана 2023-05-28 в 00 23 27](https://github.com/atls-academy/oksssvv.github.io/assets/3940885/ff4a2a58-c4b9-4f58-b913-be7c7ccc5ce0)

2023-05-28 13:22 UTC, oksssvv commented on landing/fragments/landing-ticker/src/technology/technology.component.tsx
> +  webDevelopment: 'JavaScript,HTML,CSS,SASS,Vanilla JS,Jade',
@TorinAsakura 
Таким образом?  [ссылка](https://github.com/torin-asakura/misik/blob/master/landing/fragments/landing-relocation-program-benefits/src/data/mocks/benefits/benefits.mock.ts)
не смогла найти среди проектов как выполняется запись элементов именно для бегущей строки

так не верно? ты сказал именно объекты в массиве
`export const technologyKit = {`
  `webDev: ['JavaScript','HTML','CSS','SASS','Vanilla JS','Jade'],`
  `workspace: ['Github','Atom','Figma']`
}
`

2023-05-28 21:22 UTC, TorinAsakura requested changes
в который (и последний) раз обращу твоё внимание на "некоторые" элементы требующие сверки с фигмой…

2023-05-28 21:22 UTC, TorinAsakura commented on ui/condition/src/condition.interface.ts
> +// export interface SmoothOptions {
комментированный код перед реквестом нужно убирать

2023-05-28 21:22 UTC, TorinAsakura commented on ui/condition/src/some-animations/some-animations.component.ts
> +export const AnimationVariant = {
почему назвала его some? ты вообще не понимаешь что я написал для примера? У тебя тут нет контекста применения или что?

2023-05-30 07:51 UTC, oksssvv commented
@TorinAsakura 

>в который (и последний) раз обращу твоё внимание на "некоторые" элементы требующие сверки с фигмой…

речь же о кнопке `курсы` из мобильной версии (перенос слова)?
или у тебя не отображается еще и вложенная в нее иконка?

2023-05-30 07:52 UTC, TorinAsakura commented
@oksssvv На скриншот смотри

2023-05-30 08:00 UTC, oksssvv commented
@TorinAsakura 

> На скриншоте смотри

>![image](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/f54bf65d-631f-434f-b267-075ad8c2fd55)

Судя по скрину - иконка не отображается, а другие кнопки в которых есть вложение иконки? Которые ниже
У меня просто все на месте, мне нужно понять что не так, что бы исправить

2023-05-30 08:00 UTC, TorinAsakura commented
@oksssvv у меня вопрос только к тому, что на скрине

2023-06-01 19:00 UTC, TorinAsakura requested changes
1. Warning: Received `true` for a non-boolean attribute `fill`.

If you want to write it to the DOM, pass a string instead: fill="true" or fill={value.toString()}.
    at button
    at /Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/@emotion-react-virtual-b301de22a9/4/.yarn/berry/cache/@emotion-react-npm-11.11.0-fda75c579c-9.zip/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at eval (webpack-internal:///../../../../.yarn/__virtual__/@ui-button-virtual-6366d4c56c/1/ui/button/src/button.component.tsx:36:83)
    at div
    at /Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/@emotion-react-virtual-b301de22a9/4/.yarn/berry/cache/@emotion-react-npm-11.11.0-fda75c579c-9.zip/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at div
    at /Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/@emotion-react-virtual-b301de22a9/4/.yarn/berry/cache/@emotion-react-npm-11.11.0-fda75c579c-9.zip/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at div
    at /Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/@emotion-react-virtual-b301de22a9/4/.yarn/berry/cache/@emotion-react-npm-11.11.0-fda75c579c-9.zip/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at Navigation (webpack-internal:///../../../../.yarn/__virtual__/@landing-navigation-fragment-virtual-f1fc73f6a4/1/landing/fragments/landing-navigation/src/navigation.component.tsx:37:69)
    at div
    at /Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/@emotion-react-virtual-b301de22a9/4/.yarn/berry/cache/@emotion-react-npm-11.11.0-fda75c579c-9.zip/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
    at IndexPage
    at ThemeProvider (/Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/@emotion-react-virtual-b301de22a9/4/.yarn/berry/cache/@emotion-react-npm-11.11.0-fda75c579c-9.zip/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:125:32)
    at ThemeProvider (webpack-internal:///../../../../.yarn/__virtual__/@ui-theme-virtual-8835c06af0/1/ui/theme/src/theme.provider.tsx:20:26)
    at IntlProvider (/Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/react-intl-virtual-694b2aa2d7/4/.yarn/berry/cache/react-intl-npm-6.4.2-0718017b10-9.zip/node_modules/react-intl/src/components/provider.js:88:47)
    at App (webpack-internal:///./pages/_app.tsx:22:16)
    at StyleRegistry (/Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/styled-jsx-virtual-51128919e0/4/.yarn/berry/cache/styled-jsx-npm-5.0.7-d47abf001f-9.zip/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/next-virtual-919027c60d/4/.yarn/berry/cache/next-npm-12.3.4-cdaf2db0a7-9.zip/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/next-virtual-919027c60d/4/.yarn/berry/cache/next-npm-12.3.4-cdaf2db0a7-9.zip/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/Users/torinasakura/workspace/academy/oksssvv.github.io/.yarn/__virtual__/next-virtual-919027c60d/4/.yarn/berry/cache/next-npm-12.3.4-cdaf2db0a7-9.zip/node_modules/next/dist/server/render.js:614:21)

2. Что ты там с этой кнопкой несчастной столько времени возишься Оксан?

https://github.com/atls-academy/oksssvv.github.io/assets/3940885/28a00674-6624-48b4-8e08-ba86e752b7a4

2023-06-01 19:18 UTC, TorinAsakura commented on landing/fragments/landing-ticker/src/technology/technology.component.tsx
> +  webDevelopment: 'JavaScript,HTML,CSS,SASS,Vanilla JS,Jade',
Что значит "не смогла найти как выполняется запись "ИМЕННО ДЛЯ БЕГУЩЕЙ СТРОКИ""?????

2023-06-02 13:57 UTC, TorinAsakura approved these changes
Полагаю, на 6-м степе мы с тобой обсудим вопросы адаптивности, так как это конечно же катастрофа, ну, с учётом количества примеров, которые у тебя есть под рукой

<img width="1366" alt="image" src="https://github.com/atls-academy/oksssvv.github.io/assets/3940885/5f1a8590-8d7d-4cab-be4f-7813570a4d7f">

2023-06-02 13:57 UTC, merged