Feat/landing 3
atls-academy/oksssvv.github.io pull request #26
Opened 2023-06-17 15:52 UTC by oksssvv

2023-06-21 15:41 UTC, oksssvv commented
@TorinAsakura 
**Скоуп**
Добавление анимации в проект

**Описание**
Необходимо создать анимацию прокрутки секций
В архиве проектов - не нашла реализацию данной анимации

**Контекст**
[анимация фрейма в Figmotion](https://www.figma.com/file/xtt9udyiOZRFK4eVPR8dr9/Practice-(Copy)?type=design&node-id=2238-56056&t=c0ckAucFFuyxwvuB-0)

**Вопрос**
Какие технологии использовать?
Как конкретно называется этот тип анимации? чтобы прочитать информацию о нем (не смогла найти термин в гугле)
Есть ли проект который можно взять в пример?

2023-06-22 15:24 UTC, TorinAsakura commented
> @TorinAsakura **Скоуп** Добавление анимации в проект
> 
> **Описание** Необходимо создать анимацию прокрутки секций В архиве проектов - не нашла реализацию данной анимации
> 
> **Контекст** [анимация фрейма в Figmotion](https://www.figma.com/file/xtt9udyiOZRFK4eVPR8dr9/Practice-(Copy)?type=design&node-id=2238-56056&t=c0ckAucFFuyxwvuB-0)
> 
> **Вопрос** Какие технологии использовать? Как конкретно называется этот тип анимации? чтобы прочитать информацию о нем (не смогла найти термин в гугле) Есть ли проект который можно взять в пример?

https://developer.mozilla.org/en-US/docs/Web/CSS/transition

2023-06-27 19:54 UTC, oksssvv commented
@TorinAsakura 
насколько правильно оформлен компонент и верно ли выбрана технология?

**Контекст**
[компонент](https://github.com/atls-academy/oksssvv.github.io/blob/97c4fa462740b70573bbfdebf506126627a53383/ui/layer/src/layer.component.tsx)

делала исходя из знаний, т.к. не нашла в проектах что можно взять в пример для создания

2023-06-28 06:46 UTC, TorinAsakura commented
> @TorinAsakura насколько правильно оформлен компонент и верно ли выбрана технология?
> 
> **Контекст** [компонент](https://github.com/atls-academy/oksssvv.github.io/blob/97c4fa462740b70573bbfdebf506126627a53383/ui/layer/src/layer.component.tsx)
> 
> делала исходя из знаний, т.к. не нашла в проектах что можно взять в пример для создания

вполне, только компонент должен называться parallax, он, кстати, присутствует в нашей библиотеке

2023-06-28 13:08 UTC, TorinAsakura requested changes
Издеваешься?
<img width="1366" alt="image" src="https://github.com/atls-academy/oksssvv.github.io/assets/3940885/454e42b4-8ed0-449b-93fb-9af1f1eb62b9">

2023-06-28 20:54 UTC, oksssvv commented
@TorinAsakura 
исходя из дизайна параллакс первой секции есть только на десктопе, для мобильной версии его нужно убрать, каким подходом более правильно будет воспользоваться в этом случае?

2023-06-28 20:59 UTC, oksssvv commented
> Издеваешься? <img alt="изображение" width="1366" src="https://user-images.githubusercontent.com/3940885/249479354-454e42b4-8ed0-449b-93fb-9af1f1eb62b9.png">

здесь вьюпорт менее стандартного FullHD?

2023-06-28 21:14 UTC, TorinAsakura commented
@oksssvv Дело не во вьюпорте, дело в том, что у тебя ломается сам вью, такого не должно быть, посмотри - у тебя там горизонтальный скролл и страницы как фарш. Это iPad Pro 12"9 2022, можешь посмотреть его спеки

2023-06-28 21:32 UTC, TorinAsakura commented
@oksssvv iPad, iPad Pro (12.9-inch) (5th generation)

2023-06-29 17:03 UTC, oksssvv commented
@TorinAsakura 

**для ipad'a**
![Снимок экрана от 2023-06-29 19-50-23](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/53d53ce2-6a50-45f3-9e8d-768daf942ae4)

что то подобное вижу если поставить меньший вью, между 1920x1080 и мобильной версией, но это из-за верстки под FullHD, на меньшем просто перестают умещаться блоки

**1536x864**
![Снимок экрана от 2023-06-29 19-58-41](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/d3536bee-e56c-40d8-9d87-200215d82e76)

если я правильно поняла, мне нужно чинить верстку под меньшие вьюпорты?

2023-06-29 17:03 UTC, TorinAsakura commented
@oksssvv Тебе нужно просто разрешить блокам заполнять пространство (growth) на больших разрешениях, чтобы оно не ломалось

2023-07-02 21:13 UTC, TorinAsakura approved these changes
Не делай ты этот этап так долго поставил бы тебе 9/10.
Кстати, почему параллакса нет на мобильном вью?

2023-07-02 21:14 UTC, merged