feat/landing-5
atls-academy/oksssvv.github.io pull request #30
Opened 2023-07-13 19:22 UTC by oksssvv

2023-07-16 12:19 UTC, oksssvv commented
@TorinAsakura 

**Скоуп**
Переход на страницу `Наша библиотека` 

**Описание**
При нажатии на кнопку `Все материалы` в секции `Курсы` необходимо осуществить переход на страницу `Наша библиотека` 

**Контекст**
[страница на макете](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=2326%3A5173&mode=dev)
[кнопка для перехода](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=2068%3A3546&mode=dev)

**Воспроизведение**
1. Создала отдельную страницу `library-page` рядом с `index-page`
2. Выполнила верстку страницы
3. Сделала экспортирование в `entrypoint-renderer`

**Вопрос**
Как создать переход на соседнюю страничку при клике по кнопке, какими средствами это можно реализовать?

2023-07-16 14:47 UTC, TorinAsakura commented
@oksssvv То есть, документация некста, по роутингу и примеры, которые у тебя есть- тебе не помогли?

2023-07-16 14:47 UTC, TorinAsakura commented
@oksssvv Если вкратце - есть компонент Link

2023-07-18 17:03 UTC, TorinAsakura requested changes

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <NextLink path='/library'>
Почему у тебя вёрстка обёрнута в ссылку?

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <NextLink path='/library'>
https://github.com/atls/hyperion/blob/db7f4791a25d81a82a6f2ece22f23b87d73f03ac/ui-parts/button/src/button.docs.mdx#L27

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/cards-material/cards-material.component.tsx
> +            marginBottom={[12, 0]}
зачем тут марджин?

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
>                id='/'
что это за id?

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
>                defaultMessage='Здесь собраны материалы и статьи, которые пригодятся в процессе обучения. Сюда стоит пойти за ответом на любой возникший вопрос.'
убери их

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
>              placeholder='Введите ваш запрос'
почему текст захардкоден?

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
> +            textButton='Искать'
что такое текстКнопка?

2023-07-18 17:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
> +          borderRadius={['32px 32px 0px 0px', '80px 80px 0px 0px']}
для радиусов, в теме есть сущность radii, очень странно, что ты об этом не знаешь до сих пор

2023-07-18 17:03 UTC, TorinAsakura commented on ui/button/src/button.shape-styles.ts
> +  rounding: prop('theme.radii.regular') as unknown as number,
странно, но тут ты их используешь, а в компоненте выше нет…

2023-07-18 17:03 UTC, TorinAsakura commented on ui/card/src/card-library-material/card-library-material.component.tsx
> +  }
это что ещё за новшества?

2023-07-18 17:03 UTC, TorinAsakura commented on ui/card/src/card-library-material/card-library-material.component.tsx
> +          <Box maxWidth={['335', '530']} display='inline'>
зачем тут снова инлайн я не понимаю? Ты случайно разучилась использовать Row?

2023-07-18 17:03 UTC, TorinAsakura commented on ui/card/src/card-library-material/card-library-material.component.tsx
> +                defaultMessage='Комплексный учебный материал, разработанный для студентов и всех, кто интересуется сферой дизайна,
зачем снова дефолтмесседжи?

2023-07-18 17:03 UTC, TorinAsakura commented on ui/card/src/card-library-material/card-library-material.component.tsx
> +                id='/'
ещё раз - что это за айди?

2023-07-18 21:45 UTC, oksssvv commented on ui/card/src/card-library-material/card-library-material.component.tsx
> +          <Box maxWidth={['335', '530']} display='inline'>
@TorinAsakura 
если убрать - технологии выстаиваются в линию

с `inline`
![Снимок экрана от 2023-07-19 00-41-45](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/2ebcf48f-95e4-4c37-bf13-bbab8ec833ff)

без `inline`
![Снимок экрана от 2023-07-19 00-42-13](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/da2e86be-95b0-4d50-aadb-d517ad5ea301)

2023-07-18 22:05 UTC, oksssvv commented on landing/fragments/landing-library/src/cards-material/cards-material.component.tsx
> +            marginBottom={[12, 0]}
@TorinAsakura 

с `marginBottom`
![Снимок экрана от 2023-07-19 01-00-22](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/89129763-4cd0-4f01-b203-07e647966f5c)



без `marginBottom`
![Снимок экрана от 2023-07-19 01-00-47](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/4b094889-4a73-417a-971e-f969351d3aff)

по другому - можно установить высоту боксу и сделать `justify-content: space-between`, но так вроде бы минималистичнее

2023-07-18 22:53 UTC, TorinAsakura commented on ui/card/src/card-library-material/card-library-material.component.tsx
> +          <Box maxWidth={['335', '530']} display='inline'>
ну так видимо нужно ограничить ширину блока и разрешить перенос, да?

2023-07-18 22:54 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <NextLink path='/library'>
@TorinAsakura 

- в данном случае если обернуть кнопку в линк, то слетит ширина / дисплей для вьюпортов / сжатие 0
- если только текст в линк - то только текст будет кликабелен для перехода к библиотеке, а не сама кнопка

2023-07-18 22:54 UTC, TorinAsakura commented on landing/fragments/landing-library/src/cards-material/cards-material.component.tsx
> +            marginBottom={[12, 0]}
нет, нужно вставлять лэйауты с базисами, так как если у тебя добавится или убавится строка - что тогда будет?

2023-07-23 22:52 UTC, TorinAsakura requested changes
Объясните чёрт вас дери, что за слой material и почему у тебя slider-block? Зачем эти гиперименования? Насчёт карточек - история как и у всех - не может быть ни екстендед ни дефолт ни ещё какой-либо карточки - есть карточка, у неё есть какие-то пропсы, нужна кастомная карточка в рамках фрагмента courses? Отлично, назови fragments/sources/courses.component.tsx который будет екстендить ui/cards, но не надо делать из карточки мутанта. С остальным тоже самое

2023-07-24 09:30 UTC, oksssvv commented
@TorinAsakura 
Насчет slider-block, не даст же назвать также как и импортируемый ui-компонент, тут появляется выбор, какой то компонент должен называться иначе

![Снимок экрана от 2023-07-24 12-29-13](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/f4833cf0-218a-4a72-8dd9-58bbc8ec5dac)

2023-07-24 09:31 UTC, TorinAsakura commented
@oksssvv Привязываешься. Это контейнер, но уж точно не блок.

2023-07-24 12:23 UTC, oksssvv commented
@TorinAsakura 
я верно поняла, что карточка должна выглядеть так? а прочие обвесы настраиваются там где ее используют
![image](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/561262e8-5241-4f75-b184-6b16cbc96912)

ее использование в фрагменте
![image](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/922b89b1-f386-4b59-9ac9-097fac0c2852)

уточняю что б не переписывать все карточки не правильно

2023-07-24 12:33 UTC, TorinAsakura commented
> @TorinAsakura я верно поняла, что карточка должна выглядеть так? а прочие обвесы настраиваются там где ее используют ![image](https://user-images.githubusercontent.com/126156026/255587253-561262e8-5241-4f75-b184-6b16cbc96912.png)
> 
> ее использование в фрагменте ![image](https://user-images.githubusercontent.com/126156026/255587452-922b89b1-f386-4b59-9ac9-097fac0c2852.png)
> 
> уточняю что б не переписывать все карточки не правильно

не, по месту ты задаёшь только контент, вёрстка из компонента, ну, посмотри на другие компоненты, если карточка есть больше - для этого есть пропсы как и у кнопки, карточка у тебя в проекте ведь одна

2023-07-25 00:10 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-component.tsx
> +                  5
что это?

2023-07-25 00:15 UTC, TorinAsakura requested changes
почти

2023-07-25 00:15 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
> +    <Materials divider={index > 1 ? 1 : 0} key={index} /> /*eslint-disable-line */
что такое materials?

2023-07-25 00:15 UTC, TorinAsakura commented on landing/fragments/landing-library/src/materials/data/headlines.ts
> +export const Headlines = [
я рекомендую тебе получать каждый объект отдельно, в противном случае когда ты начнёшь подключать АПИ ты сильно встрянешь)

2023-07-25 00:15 UTC, TorinAsakura commented on landing/fragments/landing-library/src/materials/materials.component.tsx
> +    {Headlines.map((title) => (
что это?

2023-07-25 00:15 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/drawer/cards/cards.desktop.tsx
> +        nameCategory={intl.formatMessage({ id: 'courses.card.education' })}
что это опять такое?

2023-07-25 00:15 UTC, TorinAsakura commented on landing/fragments/landing-process/src/slider/slider.component.tsx
> +    <Slider images={imagesMobile} widthImg='80%' heightImg='100%' display={['flex', 'none']} />
это как? а будет там под 20 штук, что будешь делать?

2023-07-25 00:15 UTC, TorinAsakura commented on ui/card/src/card.component.tsx
> +      boxShadow={hover ? '0px 0px 30px 4px rgba(123, 84, 233, 0.20)' : '0'}
куда работа с темой пропала снова?

2023-07-25 00:19 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <NextLink path='/library'>
Почитай наши гайды в юай репе, там объясняется разница между кнопками и ссылками. Если ты обернула кнопку в линк и у тебя всё поехало - значит у тебя фундаментальные проблемы с вёрсткой

2023-07-25 00:20 UTC, TorinAsakura requested changes

2023-07-25 00:20 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
>              placeholder='Введите ваш запрос'
?

2023-07-25 00:20 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
> +            textButton='Искать'
?

2023-07-25 00:20 UTC, TorinAsakura commented on landing/fragments/landing-library/src/library.component.tsx
> +          borderRadius={['32px 32px 0px 0px', '80px 80px 0px 0px']}
?

2023-07-25 13:29 UTC, oxiqod commented on landing/fragments/landing-library/src/library.component.tsx
> +    <Materials divider={index > 1 ? 1 : 0} key={index} /> /*eslint-disable-line */
@TorinAsakura 
по макету на странице библиотеки есть блок с Материалами, входит заголовок, используемыемые технологияии и дескрипция, они так и называются `Комплексный учебный материал`
поэтому я назвала этот компонент Материалы

![Снимок экрана от 2023-07-25 16-28-30](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/90f03ce3-3b26-49c2-8943-76690cb99d6b)

2023-07-25 13:30 UTC, oxiqod commented on ui/card/src/card.component.tsx
> +      boxShadow={hover ? '0px 0px 30px 4px rgba(123, 84, 233, 0.20)' : '0'}
@TorinAsakura 
исправлено в 6 степе

2023-07-25 13:39 UTC, oksssvv commented
>[TorinAsakura](https://github.com/TorinAsakura) [13 hours ago](https://github.com/atls-academy/oksssvv.github.io/pull/30#discussion_r1272874503)
?
- исправлено в 6 
>[TorinAsakura](https://github.com/TorinAsakura) [13 hours ago](https://github.com/atls-academy/oksssvv.github.io/pull/30#discussion_r1272874543)
?
- сейчас исправила в 6
>[TorinAsakura](https://github.com/TorinAsakura) [13 hours ago](https://github.com/atls-academy/oksssvv.github.io/pull/30#discussion_r1272874607)
?
- исправлено в 6

![Снимок экрана от 2023-07-25 16-38-15](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/8b8e62a8-073f-464d-a754-e040efb6ff13)

2023-07-25 13:46 UTC, oxiqod commented on landing/fragments/landing-courses/src/cards/cards-component.tsx
> +                  5
@TorinAsakura 

там одна цифра, ее тоже через react-intl пропускать?

![Снимок экрана от 2023-07-25 16-40-10](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/dd717c89-98ab-4661-8e8c-9ab7d011c07a)

2023-07-25 14:00 UTC, oksssvv commented on landing/fragments/landing-library/src/library.component.tsx
> +            textButton='Искать'
@TorinAsakura 
текст передающийся в кнопку, что б не хардкодить ее 
или опять проблемма с неймингом?

![Снимок экрана от 2023-07-25 16-59-20](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/6ac23ccd-3e91-4c54-9917-603b2575960a)


![image](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/16bd48b6-9729-4d9e-a8df-e6417f7b1a15)

2023-07-25 15:51 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <NextLink path='/library'>
@TorinAsakura 

а так? в драм-ине подсмотрела, в таком случае ничего не ломается

![Снимок экрана от 2023-07-25 18-49-55](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/ce3353a9-a9c8-4e81-baf2-261fb6c242b8)

2023-07-25 16:06 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <NextLink path='/library'>
Да, так норм

2023-07-25 16:06 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-component.tsx
> +                  5
все

2023-07-25 16:23 UTC, oksssvv commented
@TorinAsakura 
все поправила, запросила, касаемо моментов не из темы и хардкод текста в инпутах - в 6 это все сделала еще пару дней назад

2023-07-25 23:56 UTC, TorinAsakura approved these changes

2023-07-25 23:56 UTC, merged