feat/landing-6
atls-academy/oksssvv.github.io pull request #32
Opened 2023-07-19 13:23 UTC by oksssvv

2023-07-19 13:45 UTC, Nelfimov commented on ui/theme/src/theme/breakpoints.ts
> +breakpoints.superWide = breakpoints[2] // eslint-disable-line
Тут у тебя повторение индекса.

2023-07-19 13:50 UTC, oksssvv commented on ui/theme/src/theme/breakpoints.ts
> +breakpoints.superWide = breakpoints[2] // eslint-disable-line
@Nelfimov  
если это пофиксить - все равно не работают брейкпоинты

2023-07-19 13:53 UTC, oxiqod commented on ui/theme/src/theme/breakpoints.ts
> +breakpoints.superWide = breakpoints[2] // eslint-disable-line
@Nelfimov 
этот файл сейчас ничего не делает, брейкпоинты работают из коробки 
(я не могу найти как их можно переопределить, что бы брейкпоинты принимали значения которые я указываю в этом файле)

2023-07-22 13:56 UTC, oksssvv commented
@TorinAsakura 

**Вопрос**
В этом случае нужно использовать unicode или прям символ стрелки вставить в компонент <Text>?
не совсем поняла как это должно выглядеть

**Контекст**
[Элемент макета](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=2325%3A4507&mode=dev)

2023-07-22 15:35 UTC, TorinAsakura commented
@oksssvv Это иконка…

2023-07-23 22:57 UTC, TorinAsakura requested changes
Карточки…

2023-07-23 22:57 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      flexDirection='column'
почему бы просто не добавить <Column>?

2023-07-23 22:57 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      bottom={{ wide: -450 }}
а если viewport изменится? Тогда что?

2023-07-23 22:57 UTC, TorinAsakura commented on landing/fragments/landing-steps/src/item/item.component.tsx
>            backgroundColor='background.ghost'
зачем тебе две директивы центрирования когда у тебя один элемент да ещё и в роу?

2023-07-24 20:21 UTC, oksssvv commented on landing/fragments/landing-steps/src/item/item.component.tsx
>            backgroundColor='background.ghost'
@TorinAsakura 

это цифра в центре, а в роу т.к. там далее направление элементов по иксу 

![Снимок экрана от 2023-07-24 23-19-16](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/f3450310-f478-443a-be11-aac5d8abe78b)

2023-07-24 20:25 UTC, oksssvv commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      bottom={{ wide: -450 }}
@TorinAsakura 
соушллинки просто на широких форматах уходят в блок `info`
мне переиспользовать компонент `SocialLink` в другом фрагменте или правильнее будет слить хиро и инфо в один фрагмент чтобы не пользоваться абсолютным позиционированием?

**Контекст**
![Снимок экрана от 2023-07-24 23-23-29](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/f8aaa76b-29ea-45d6-8e1e-47403ed894b6)

2023-07-24 20:28 UTC, oksssvv commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      flexDirection='column'
@TorinAsakura 

Если про замену `Box` на `Column`, то коламн не реагирует на позиционирование

2023-07-24 23:47 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      flexDirection='column'
> @TorinAsakura
> 
> Если про замену `Box` на `Column`, то коламн не реагирует на позиционирование

Неужели? А в чём разница между Box и Column?

2023-07-24 23:48 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +      bottom={{ wide: -450 }}
Вообще не понял причём тут следующий фрагмент и хиро

2023-07-25 16:08 UTC, TorinAsakura requested changes
а чо у тебя кнопка инпатом сделана?

2023-07-25 23:59 UTC, TorinAsakura commented
Одна из основных твоих болей это то, что ты просто косметически скрываешь неиспользуемые элементы, которые, тем не менее потребляют ресурсы. Обрати внимание на все элементы которым ты задаёшь display: none при десктопной версии
![Снимок экрана 2023-07-26 в 02 54 35](https://github.com/atls-academy/oksssvv.github.io/assets/3940885/0d017ef8-23ae-42cd-a00b-be04133f183e)

2023-07-28 15:33 UTC, oksssvv commented
@TorinAsakura 
>а чо у тебя кнопка инпатом сделана?

она ж получается как вложенная по макету

![Снимок экрана от 2023-07-28 18-33-10](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/7f2b4170-9b45-45a2-92ab-2a3414514e17)

2023-07-28 15:41 UTC, TorinAsakura commented
@oksssvv https://github.com/atls/hyperion/blob/master/ui-parts/input/src/addon/addon.styles.ts

2023-07-28 18:14 UTC, TorinAsakura commented
> @TorinAsakura
> 
> > а чо у тебя кнопка инпатом сделана?
> 
> она ж получается как вложенная по макету
> 
> ![Снимок экрана от 2023-07-28 18-33-10](https://user-images.githubusercontent.com/126156026/256865885-7f2b4170-9b45-45a2-92ab-2a3414514e17.png)

https://getbootstrap.com/docs/5.3/forms/input-group/#button-addons

2023-07-29 17:27 UTC, oksssvv commented
@TorinAsakura 

добавила `Condition` в проект, применяю с хуком `useWindow`, все работает исправно за исключением рендера страницы при обновлении, на секунду вылетает артефакт в виде элементов которые скрыты на десктопной версии (используются в мобильной)

это происходит из-за дефолтного значения useState в хуке, т.к. стоит 0 - и он подгружает сначала нулевое значение, а затем какое указано при использовании хука

если поставить значение [windowWidth, setWindowWidth] = useState(1960) например, то десктоп грузится исправно, но при обновлении на мобильной версии - то на секунду артефакт будет уже в виде десктопных элементов

[ссылка на файл хука](https://github.com/atls-academy/oksssvv.github.io/blob/2edea82b089ff7cc7173e77e3562b92c7fafa9d0/ui/utils/src/hooks/use-window.hook.ts)

загрузка страницы:
![Снимок экрана от 2023-07-29 20-09-44](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/e1d74205-5b15-40ab-9b6e-140f14a44580)

через секудну после:
![Снимок экрана от 2023-07-29 20-09-38](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/d043b752-4fb1-49f6-b149-eb47b8b19718)


не могу прийти к выходу из ситуации
каким способом воспользоваться для решения этой проблемы?

2023-07-29 20:24 UTC, TorinAsakura commented
> @TorinAsakura
> 
> добавила `Condition` в проект, применяю с хуком `useWindow`, все работает исправно за исключением рендера страницы при обновлении, на секунду вылетает артефакт в виде элементов которые скрыты на десктопной версии (используются в мобильной)
> 
> это происходит из-за дефолтного значения useState в хуке, т.к. стоит 0 - и он подгружает сначала нулевое значение, а затем какое указано при использовании хука
> 
> если поставить значение [windowWidth, setWindowWidth] = useState(1960) например, то десктоп грузится исправно, но при обновлении на мобильной версии - то на секунду артефакт будет уже в виде десктопных элементов
> 
> [ссылка на файл хука](https://github.com/atls-academy/oksssvv.github.io/blob/2edea82b089ff7cc7173e77e3562b92c7fafa9d0/ui/utils/src/hooks/use-window.hook.ts)
> 
> загрузка страницы: ![Снимок экрана от 2023-07-29 20-09-44](https://user-images.githubusercontent.com/126156026/256997520-e1d74205-5b15-40ab-9b6e-140f14a44580.png)
> 
> через секудну после: ![Снимок экрана от 2023-07-29 20-09-38](https://user-images.githubusercontent.com/126156026/256997534-d043b752-4fb1-49f6-b149-eb47b8b19718.png)
> 
> не могу прийти к выходу из ситуации каким способом воспользоваться для решения этой проблемы?

на твоё усмотрение

2023-07-30 13:33 UTC, oksssvv commented
@TorinAsakura 
>на твоё усмотрение

не получается это пофиксить, помоги разобраться как решить эту проблему

2023-07-30 13:35 UTC, TorinAsakura commented
@oksssvv Откатись на дисплей. Уже нет времени.

2023-07-31 23:27 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +            waves
всегда делай признаки явными, так удобнее работать с кодом, сделай ради приличия хотя бы булен

2023-07-31 23:31 UTC, TorinAsakura commented on ui/card/src/card.component.tsx
> +    // <Background backgroundColor='waves' backgroundPosition='500px 100px' backgroundRepeat='no-repeat' display={{_:'none',standard:'none',wide:'flex',ultra:'flex'}} width='100%'>
что это?

2023-07-31 23:32 UTC, TorinAsakura approved these changes
Почисти комменты и 👍

2023-08-01 13:34 UTC, oksssvv commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +            waves
@TorinAsakura 
линт в таком случае будет ругаться, что значение может быть опущено
`Error: Value must be omitted for boolean attributes react/jsx-boolean-value`

я тогда переименую пропс, и немного по другому использую, передам путь к изображению

2023-08-01 14:08 UTC, TorinAsakura approved these changes

2023-08-01 14:09 UTC, merged