feat/landing-7
atls-academy/oksssvv.github.io pull request #34
Opened 2023-08-08 18:36 UTC by oksssvv

2023-08-14 06:48 UTC, Nelfimov requested changes
Много багов в дизайне:

1. Заголовок индекса - на весь экран моего ноута (1440х900):

<details>

![image](https://github.com/atls-academy/oksssvv.github.io/assets/44067768/78940926-30cf-461a-a1a3-3aaf687fcb24)

</details>

2. Верхнее меню - его появление растягивает вьюпорт в ширину, так же не работает листание курсов:

<details>

<img width="1552" alt="Screenshot 2023-08-14 at 09 37 56" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/f6b68a24-e84a-403a-8c24-b632fc9840d6">

</details>

3. Параллакс слишком быстро перекрывает низ блока:

<details>

<img width="1552" alt="Screenshot 2023-08-14 at 09 38 14" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/3ded711b-5f2d-4469-b124-a5c55a38c11a">

<img width="1552" alt="Screenshot 2023-08-14 at 09 38 30" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/73374910-5c02-4c3b-b8d4-558c68f6705d">

</details>

4. Нет картинок у курсов:

<details>

<img width="1552" alt="Screenshot 2023-08-14 at 09 38 20" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/1fad8dc1-6808-4e6a-8d3c-4f32e05578b2">

</details>

6. В мобильном виде верхняя кнопка "Курсы" с переносом

<details>

<img width="1552" alt="Screenshot 2023-08-14 at 09 40 39" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/79f8afec-0945-46c0-9063-d91d9b07f05d">

</details>

7. Поиск в библиотеке - при активности границы не подсвечиваются как в дизайне, кнопка с переносом слова:

<details>

<img width="1552" alt="Screenshot 2023-08-14 at 09 41 41" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/fc9e60bc-b1c6-45d8-a5fb-88c1be30c808">

</details>

2023-08-14 12:45 UTC, oxiqod commented
@Nelfimov 
поправила, насчет карточек - их ж нет в fullHD, изображения в карточках по макету отображаются при вью от 2560px

2023-08-15 07:49 UTC, Nelfimov requested changes
Есть правки в дизайне:
- Картинки карточек курсов есть везде кроме мобильного вида
- брейкпоинт для перехода десктоп - мобильный ниже чем у тебя установлен. Выбор конкретного значения на твое усмотрение.

См. комменты в фигме.

2023-08-15 08:04 UTC, oksssvv commented
@Nelfimov 
не поняла почему возник вопрос что менее 2560px ширины вью - выставляется мобильная
у меня порог стоит на 1280px, менее этой ширины вьюпорта заканчивается десктоп - начинается мобайл

нашла информацию что десктопная версия идет до 980px - затем начинается мобильная, так сделать?

2023-08-15 08:06 UTC, Nelfimov commented
Попробуй 980. Важно чтобы брейкпоинт соответствовал наличию места на странице и не возникало больших пустот.

2023-08-15 08:26 UTC, oksssvv commented
@Nelfimov 
>Попробуй 980. Важно чтобы брейкпоинт соответствовал наличию места на странице и не возникало больших пустот.
тут не в пустотах дело, а наоборот

при 1000px ширины вью например вот так:

![Снимок экрана от 2023-08-15 11-24-58](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/f937f567-0e04-4e59-8725-f6c54dd44c3c)

2023-08-17 07:05 UTC, Nelfimov requested changes

2023-08-17 07:05 UTC, Nelfimov commented on landing/entrypoints/renderer/package.json
> +    "@apollo/client": "3.7.17",
Зависимость лишняя т.к. у тебя выше уже есть.

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-courses/src/cards/details/details.component.tsx
> +  return (
Необходимо перевести в запрос `graphql`, данные добавил:

```graphql
query NewQuery {
  courseBy(id: "cG9zdDoyNzk=") {
    content
    course {
      title
      label {
        ... on Label {
          title
        }
      }
      description
    }
  }
}
```

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-courses/src/cards/wideScreen/transition-card/transition-card.component.tsx
> +              <FormattedMessage id='courses.all-materials' />
Так же переводим в `graphql`:

```graphql
query NewQuery {
  navigationBy(id: "cG9zdDoyODM=") {
    navigation {
      linkName
    }
    title
  }
}
```

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +            key={index}
Индексы действительно плохая практика. Может перейти на `title` с удалением пробелов?

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-faq/src/feedback/feedback.component.tsx
> +              <FormattedMessage id='faq.ask-us-question' />
Добавил `graphql`:

```graphql
query NewQuery {
  navigationBy(id: "cG9zdDoyODQ=") {
    title
  }
}
```

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-faq/src/faq.component.tsx
> +                <FormattedMessage id='faq.ask-question' />
```graphql
query NewQuery {
  navigationBy(id: "cG9zdDoyODQ=") {
    title
  }
}
```

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-faq/src/faq.component.tsx
> +                <FormattedMessage id='faq.ask-question' />
```graphql
query NewQuery {
  navigationBy(id: "cG9zdDoyODQ=") {
    title
  }
}
```

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-faq/src/faq.component.tsx
> +              <FormattedMessage id='faq.ask-question' />
```graphql
query NewQuery {
  navigationBy(id: "cG9zdDoyODQ=") {
    title
  }
}
```

2023-08-17 07:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/navigation.component.tsx
>              <Button
Измени курсы на запрос `graphql`, в навигации есть.

2023-08-17 07:05 UTC, Nelfimov commented on ui/form/src/form.component.tsx
> +          <FormattedMessage id='faq.form.we-got-your-question' />
Добавил для формы `graphql`:

```graphql
query NewQuery {
  allForms {
    nodes {
      title
      id
      forms {
        text
        type {
          ... on Label {
            title
          }
        }
      }
    }
  }
}
```

2023-08-17 13:27 UTC, oksssvv commented
@Nelfimov 
всё вышеуказанное исправила, раз уж все данные с сервера получаем, то что насчет странички `Library`? ее верстка почти полностью статична

2023-08-17 17:50 UTC, Nelfimov commented
Сделал данные для Library:

Hero:

<details>

```graphql
query NewQuery {
  sections {
    nodes {
      sections {
        title
        navigationName
      }
      content
      id
    }
  }
}
```

</details>

Материалы:

<details>

```graphql
query NewQuery {
  allTutorials {
    nodes {
      learningMaterials {
        description
        skills {
          ... on Skill {
            title
          }
        }
      }
      id
    }
  }
}
```

</details>

2023-08-21 11:19 UTC, Nelfimov requested changes

2023-08-21 11:19 UTC, Nelfimov commented on ui/navbar/src/navbar.component.tsx
> +  const reverseLinks = getLinks?.reverse()
Нехорошо привязываться к `reverse`, лучше элементы зашить четко по ID.

2023-08-21 11:19 UTC, Nelfimov commented on ui/form/src/form.component.tsx
> +          placeholder={form?.data?.allForms.nodes[6].forms.text}
Здесь и далее - ты зависишь от порядка ответа сервера. Лучше перейти на привязку к ID.

2023-08-21 11:19 UTC, Nelfimov commented on ui/card/src/card.component.tsx
>        {props.image ? (
Лучше перейти на `<Condition>`

2023-08-21 11:19 UTC, Nelfimov commented on ui/accordion/src/accordion.component.tsx
>                      fontSize={{ _: 'medium', standard: 'standard', wide: 'major', ultra: 'major' }}
Переходи выше на `Condition`

2023-08-21 11:19 UTC, Nelfimov commented on ui/accordion/src/accordion.component.tsx
> +  const answer = useFaq()
В `ui` хранятся переиспользуемые компоненты. А тут мы зашиваем конкретное значение. Его лучше передавать через пропсы.

2023-08-29 11:00 UTC, oxiqod commented on ui/form/src/form.component.tsx
> +          placeholder={form?.data?.allForms.nodes[6].forms.text}
@Nelfimov 
не совсем понимаю как это реализовать, я получаю массив с объектами, внутри каждого хранится id:

<details>

``` 
"nodes": [
        {
          "id": "cG9zdDozMDA=",
          "forms": {
            "text": "Мы получили твой вопрос, вернёмся с ответом asap."
          }
        },
        {
          "id": "cG9zdDoyOTk=",
          "forms": {
            "text": "«Соглашение об обработке персональных данных»"
          }
        },
        {
          "id": "cG9zdDoyOTg=",
          "forms": {
            "text": "Нажимая на кнопку «Оставить заявку», вы принимаете"
          }
        },
        {
          "id": "cG9zdDoyOTY=",
          "forms": {
            "text": "Отправить сообщение"
          }
        },
        {
          "id": "cG9zdDoyOTU=",
          "forms": {
            "text": "Телефон"
          }
        },
        {
          "id": "cG9zdDoyOTQ=",
          "forms": {
            "text": "Имя"
          }
        },
        {
          "id": "cG9zdDoyOTM=",
          "forms": {
            "text": "Сообщение"
          }
        }
      ]
```

</details>


я делала доступ к данным например через `map(el=>el.data)` и `nodes[index]`, как получать доступ по другому?

получается что внутри массива все равно приходится делать поиск нужного объекта с данными используя индекс например - `nodes[3].id`

2023-09-06 09:16 UTC, Nelfimov commented on ui/form/src/form.component.tsx
> +          placeholder={form?.data?.allForms.nodes[6].forms.text}
У тебя каждая нода обладает своим ID. Ты ведь можешь их захардкодить и подставлять туда, где ожидаешь инфо по этому ID.

Изменение элемента, его ID, уже будет считаться ломающим изменением, которое конечно же повлечет изменение кода. Но иначе ты сильно зависишь от порядка элементов в ответе сервера.

2023-09-06 09:17 UTC, Nelfimov requested changes
Правки + ID нод

2023-09-06 09:18 UTC, oksssvv commented on ui/form/src/form.component.tsx
> +          placeholder={form?.data?.allForms.nodes[6].forms.text}
@Nelfimov 

только что исправила и ревью запросила, посмотри как время будет

2023-09-07 05:41 UTC, Nelfimov requested changes

2023-09-07 05:41 UTC, Nelfimov commented on ui/navbar/package.json
> +    "graphql": "16.7.1",
`graphql` тоже можно в `peer` - он отдается у тебя в энтрипоинте

2023-09-07 05:41 UTC, Nelfimov commented on ui/form/package.json
> +    "graphql": "16.7.1",
Можно в `peer`

2023-09-07 05:41 UTC, Nelfimov commented on ui/condition/package.json
> +  "main": "src/index.ts"
можно переиспользовать наш - `@atls-ui-parts/condition`

2023-09-07 05:41 UTC, Nelfimov commented on landing/fragments/landing-faq/src/feedback/feedback.component.tsx
> +export const Feedback = ({ open, onClose }) => {
Интерфейсы

2023-09-07 05:41 UTC, Nelfimov commented on landing/fragments/landing-library/src/materials/item/item.component.tsx
>  export const Item = ({ ...props }) => {
Интерфейс

2023-09-07 05:41 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/item/item.component.tsx
> +      {path && (
`Condition` сюда хорошо впишется

2023-09-07 18:26 UTC, Nelfimov approved these changes

2023-09-07 18:42 UTC, oksssvv commented
В последнем коммите - поправила то, что забыла ^

2023-09-08 14:38 UTC, TorinAsakura requested changes
основные претензии это разного рода вычисления "на лету" вроде             {hero?.data?.sections.nodes[6].sections.title.split(' ').slice(0, -1).join(' ')}
и прочих, которые создают нестабильность при работе с данными, то есть, любое смещение в массиве и мы получим  не то, что ожидается

2023-09-08 14:38 UTC, TorinAsakura commented on globals/data/src/helpers/get-client.helper.ts
> +    uri: 'https://wp.api.atls.academy/graphql',
вынести в env

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/details/details.component.tsx
> +  return (
статус?

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/helpers/get-gap.ts
> +export const getGap = (index) =>
что это вообще, а главное для чего?

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/wideScreen/wideScreen.component.tsx
>              index < 3
это тут для чего?

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/wideScreen/wideScreen.component.tsx
> +              : card?.data?.courses.nodes[1].course.title
как это контролировать в будущем?

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +  const content = getId('cG9zdDoyMjc=')?.content
почему у тебя айди объекта получается тут, прямо в компоненте?

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                {atlantisInfo?.slice(0, 3).join(' ')}
зачем тут слайс и джойн?

2023-09-08 14:38 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-links/social-links.component.tsx
> +export const SocialLinks: FC<SocialLinksProps> = ({ buttonSize, iconWidth, iconHeight, gap }) => (
почему у тебя внешние ссылки как path? где target?

2023-09-08 17:14 UTC, oksssvv commented on landing/fragments/landing-courses/src/cards/helpers/get-gap.ts
> +export const getGap = (index) =>
@TorinAsakura 
получение размера флексБазиса для увеличения расстояния между категорией и заголовком в карточке, сделала в таком виде т.к оно делится на 3 (например в обычном FullHD расстояния - первая карточка: 214px, вторая карточка: 56px, все следующие: 110px)

2023-09-08 17:20 UTC, oksssvv commented on landing/fragments/landing-courses/src/cards/wideScreen/wideScreen.component.tsx
>              index < 3
@TorinAsakura 

получение заголовка, единственное что надо вынести в тело функции, ну и привязку по ID, сделаю
![Снимок экрана от 2023-09-08 20-16-13](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/5bf2b862-0cd4-4218-ba10-fdcda223d97b)

2023-09-08 17:34 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                {atlantisInfo?.slice(0, 3).join(' ')}
@TorinAsakura 

с сервера приходит сплошной текст, в теле функции я его разделила что бы получить 2 предложения, а дальше пришлось слайсить и джойнить что бы менять цвет некоторым словам

![Снимок экрана от 2023-09-08 20-33-41](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/348618cc-4f59-419d-a9ba-a02e8d958fc1)

2023-09-08 17:39 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
> +  const content = getId('cG9zdDoyMjc=')?.content
@TorinAsakura 

он ж просто прогоняется через функцию `getId` что б привязаться к определенному ID с сервера, в дальнейшем если будет смещение элементов массива - текст который я дальше использую - не слетит

2023-09-10 23:56 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                {atlantisInfo?.slice(0, 3).join(' ')}
Это гипернеочевидно. Либо JDoc делай либо делай по-человечески через CSS, если сложно - оставь как есть

2023-09-10 23:59 UTC, TorinAsakura approved these changes

2023-09-10 23:59 UTC, merged