feat: authorization mechanism
atls-academy/oksssvv.github.io pull request #7
Opened 2023-03-18 11:23 UTC by oksssvv

2023-03-18 13:51 UTC, eshevlyakova commented on authorizaion.ts
> +let userData:Array<string[]> = [
Неправильная типизация переменной, нужно более подробно написать какие там должны быть значения

2023-03-18 13:51 UTC, eshevlyakova commented on authorizaion.ts
> +  ['Oksana','010101']
Во первых что такое 'Oksana' или '010101', здесь нецелесообразно использовать массив. Во вторых у тебя пользователя еще нет, а данные какие-то есть

2023-03-18 13:51 UTC, eshevlyakova commented on authorizaion.ts
> +function whoami(currentSession:string|null):string{
Везде используй стрелочные функции

2023-03-18 13:51 UTC, eshevlyakova commented on authorizaion.ts
> +let activeSession:string|null = userData[2][0];
Все данные пользователя можно хранить в одном месте. Какие данные для одного юзера у нас вообще существуют?

2023-03-18 13:51 UTC, eshevlyakova commented on authorizaion.ts
Плюс код не удовлетворяет требованиям lint
Для проверки используй `yarn lint` у себя в репозитории

2023-03-18 16:50 UTC, oksssvv commented on authorizaion.ts
@eshevlyakova 

**Вопрос**
1. Куда ввести команду yarn heck?

2023-03-18 17:00 UTC, eshevlyakova commented on authorizaion.ts
@oksssvv 
> Куда ввести команду yarn heck?

В консоли проекта

2023-03-19 10:46 UTC, eshevlyakova reviewed
Код не проходит проверки линта. Перед тем как сделать коммит запускай команду `yarn check` - она форматирует твой код, и проверяет на ошибка линта (https://blog.vverh.digital/2022/what-is-linter-chto-takoe/) и соответствие типов.

Также не нужно называть так коммит: что значит обновила? Ты через неделю уже забудешь, что там делала) Нужно писать, что конкретно исправила в коде

2023-03-19 10:46 UTC, eshevlyakova commented on authorizaion.ts
> +const session = <K> []
Когда я говорила про данные пользователя в одном месте. Я имела ввиду использовать interface (https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#interfaces)
Создаешь интерфейс для одного юзера со всеми его данными (авторизирован или нет, логин и пароль). Учти какие-то данные обязательные, а какие-то нет. 
Потом создаешь переменную пользователя на основе интерфейса, заполняешь то, что сразу известно и изменяешь объект данных в различных функциях

2023-03-19 12:50 UTC, oksssvv commented
@eshevlyakova 

**Вопрос**
1. При попытке совершить проверку yarn check выводит ошибки, исходя из логов приложенных ниже, в чем может быть проблема?

`PS C:\Users\Mamba\Desktop\oksssvv.github.io> yarn check
(node:8180) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
➤ YN0000: ┌ Format
➤ YN0000: └ Completed in 0s 463ms
➤ YN0000: Done in 0s 465ms
➤ YN0000: ┌ Typecheck
➤ YN0000: │ ENOENT: no such file or directory, chdir 'C:\Users\Mamba\Desktop\oksssvv.github.io' -> '/C:/Users/Mamba/Desktop/oksssvv.github.io'
➤ YN0000: │
➤ YN0000: │ wrappedChdir                                                                                                                   node:internal/bootstrap/switches/does_own_process_state:112:14➤ YN0000: │ process.chdir                                                                                                                                                      node:internal/worker:106:5➤ YN0000: │ process.chdir.process.chdir                                                                                                 .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:390:27675➤ YN0000: │ NQ.check                                                                                                                     .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:2445:261➤ YN0000: │                                                                                                                              .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:2456:863➤ YN0000: │ Ewt.startSectionPromise                                                                                                      .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:298:3501➤ YN0000: │ Ewt.startTimerPromise                                                                                                        .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:298:4397➤ YN0000: │                                                                                                                              .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:2456:747➤ YN0000: │ Ewt.start                                                                                                                    .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:298:2558➤ YN0000: │ Dse.execute                                                                                                                  .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:2456:678➤ YN0000: │ async Dse.validateAndExecute                                                                                                 .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:81:13125➤ YN0000: │ async y9.run                                                                                                                  .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:95:2700➤ YN0000: │ async Gte.execute                                                                                                            .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:2442:431➤ YN0000: │ async Gte.validateAndExecute                                                                                                 .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:81:13125➤ YN0000: │ async y9.run                                                                                                                  .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:95:2700➤ YN0000: │ async y9.runExit                                                                                                              .yarn/releases/yarn-0.0.1-git.20221031.hash-e5a4f7d.cjs:95:2884➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 87ms
➤ YN0000: ┌ Lint
➤ YN0000: └ Completed in 1s 261ms
➤ YN0000: Done in 1s 262ms`

2023-03-19 13:34 UTC, eshevlyakova commented
@oksssvv 

- Ты код в WebStorm пишешь? И какая ОС?

2023-03-19 13:36 UTC, oksssvv commented
@eshevlyakova 

> * Ты код в WebStorm пишешь? И какая ОС?

IDE - VS Code
OC - Windows

2023-03-19 13:40 UTC, eshevlyakova commented
@oksssvv @oksssvv мы работаем только в WebStorm. Установи его

2023-03-19 16:30 UTC, eshevlyakova commented
@oksssvv 

Cделай в консоли у себя в репозитории
`yarn husky install .config/husky && runas icacls +x .config/husky/pre-commit`
После этого сделай `yarn check` и если также вылезает ошибка, то скинь логи

2023-03-19 16:32 UTC, oksssvv commented
> @oksssvv
> 
> Сделай в консоли у себя в репозитории `yarn husky install .config/husky && runas icacls +x .config/husky/pre-commit` После этого сделай `yarn check`и если также вылезает ошибка, то скинь логи

**Логи**

```
PS C:\Users\Mamba\Desktop\oksssvv.github.io> yarn husky install .config/husky && runas icacls +x .config/husky/pre-commit
строка:1 знак:34
+ yarn husky install .config/husky && runas icacls +x .config/husky/pre ...          
+                                  ~~                                                
Лексема "&&" не является допустимым разделителем операторов в этой версии.           
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine                                       
                                                                                     
PS C:\Users\Mamba\Desktop\oksssvv.github.io>    
```

2023-03-22 07:13 UTC, oksssvv commented
**Скоуп**
Присваивание значений свойств пользователя

**Описание**
Проверка выбрасывает ошибку при изменении внутри функции свойств объекта

**Ожидаемое поведение**
Возможность валидно изменить значение свойств объекта Пользователя

**Вопрос**
Каким способом корректно это осуществить?

2023-03-22 10:56 UTC, eshevlyakova commented
@oksssvv 
Сразу несколько замечаний:
1. Зачем ты сразу создаешь двух пользователей? У тебя должен быть один пользователь, который изначально не авторизирован и с помощью твоих функций можно выполнять регистрацию, выход и тд. В условии задания не написана поддержка нескольких пользователей
2. Также в условии задания написано при не прохождении каких-то условий выбрасывать ошибку. Конструкция if точно не удовлетворяет это требование
3. [Я в ревью](https://github.com/atls-academy/oksssvv.github.io/pull/7#:~:text=%D0%A3%D1%87%D1%82%D0%B8%20%D0%BA%D0%B0%D0%BA%D0%B8%D0%B5%2D%D1%82%D0%BE%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%2C%20%D0%B0%20%D0%BA%D0%B0%D0%BA%D0%B8%D0%B5%2D%D1%82%D0%BE%20%D0%BD%D0%B5%D1%82.) специально акцентировала твое внимания на том, что какие-то данные обязательные, а какие-то нет. То есть по умолчанию у нашего юзера нет таких свойств, как логин и пароль. А у тебя там пустые строки. [Почитай это](https://metanit.com/web/typescript/3.3.php#:~:text=%D0%9D%D0%B5%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0%20%D0%B8%20%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0%20%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D0%B4%D0%BB%D1%8F%20%D1%87%D1%82%D0%B5%D0%BD%D0%B8%D1%8F)

Насчет твоего вопроса:
> Каким способом более валидно осуществлять изменение значений у свойств?

Зачем ты изменения переменной написала в return? В return нужно писать значение, которое вернет (в твоем случае) конструкция if. То есть изменяй переменную внутри if, а уже на следующей строке пиши return и что хочешь вернуть

2023-03-22 17:32 UTC, oksssvv commented
@eshevlyakova 

**Скоуп**
Изменение значения свойства

**Описание**
Проверка lint - выбрасывает ошибку при попытке удалить или изменить значение свойства объекта user внутри функции

**Контекст**
[коммит](https://github.com/atls-academy/oksssvv.github.io/pull/7/commits/9ee6360a603a9a5fe48d7086d55f38ec38253a9e#diff-a3f485405c8ff9c9de1a9340ca251591e702a15a14ff9fde37b26840283f671dR45)

**Ожидаемое поведение**
Изменение значения свойства session объекта user с целью совершения logout'a пользователя

**Логи**
`
➤ YN0000: ┌ Lint
➤ YN0000: │ authorizaion.ts:45:12
➤ YN0000: │ 
➤ YN0000: │   Error: Assignment to property of function parameter 'us'. no-param-reassign
➤ YN0000: │ 
➤ YN0000: │   43 | const logout = (us: User): string => {
➤ YN0000: │   44 |   if (us.session === true) {
➤ YN0000: │ > 45 |     delete us.session
➤ YN0000: │      |            ^
➤ YN0000: │   46 |   } else throw error[4]
➤ YN0000: │   47 |   return `You have successfully logout of ${us.username} session`
➤ YN0000: │   48 | }
➤ YN0000: │ 
➤ YN0000: └ Completed in 1s 622ms
`

**Вопрос**
Как в данной ситуации валидно осуществить изменение значения свойства объекта?

2023-03-22 17:59 UTC, eshevlyakova commented
@oksssvv 

> Как в данной ситуации валидно осуществить изменение значения свойства объекта?

Изменить можно спокойно без ошибок линта, а ты зачем то удаляешь свойство объекта. Хотя у тебя свойство session это булево значение => его можно изменить на false, вместо удаления.
И также насчет обязательных данных,[ я писала](https://github.com/atls-academy/oksssvv.github.io/pull/7#:~:text=Учти%20какие-то%20данные%20обязательные%2C%20а%20какие-то%20нет.), что лишь некоторые необязательные, а не все.
Какое свойство/свойства есть у юзера всегда? И чему оно равно по умолчанию?

2023-03-22 18:05 UTC, oksssvv commented
@eshevlyakova 

> Изменить можно сразу без ошибок, а ты зачем удаляешь свойство объекта. Хотя у тебя свойство session это булево значение => его можно изменить на false, вместо удаления. 

До `delete` я пробовала `false` - линт также выдавал ошибку переприсвоения значения свойства

Насчет обязательных данных - завтра пофиксю

2023-03-22 18:07 UTC, eshevlyakova commented
@oksssvv 

> До delete я пробовала false - линт также выдавал ошибку переприсвоения значения свойства
>
> Насчет обязательных данных - завтра пофиксю

Когда решишь вопрос обязательных и нет данных, первая решится сама собой. Как решишь, обьясню почему линт ругался

2023-03-23 06:39 UTC, eshevlyakova commented on authorizaion.ts
> +  session?: boolean
Объясни выбор типов и их обязательность для каждого свойства

2023-03-23 06:39 UTC, eshevlyakova commented on authorizaion.ts
> +  } else throw error[5]
Используй конструкцию try...catch для всех функций

2023-03-23 06:56 UTC, oksssvv commented on authorizaion.ts
> +  session?: boolean
> Объясни выбор и их обязательность для каждого свойства

**username и password**
- тип `string` обязателен, т.к. при совершении  register и login необходимо вводить данные, буквы или цифры, лучше всего для этого подходит данный тип
- тип `undefined` обязателен, т.к. у объекта пользователя изначально должны быть свойства username и password, которые по логике до совершения регистрации пользователя - неопределены, этот тип подходит для реализации данной задачи

**session**
- тип `boolean` обязателен, т.к. в последующих функциях необходимо использование данного свойства и его значение должно указывать на 2 варианта событий, активна сессия или нет, данный тип хорошо подходит в такой ситуации

2023-03-23 07:03 UTC, eshevlyakova commented on authorizaion.ts
> +  session?: boolean
Почему ты пишешь что у тебя все 3 свойства обязательны? Если в коде не так. Что означает знак вопроса перед двоеточием?


> у объекта пользователя изначально должны быть свойства username и password

Почему? Когда любой юзер первый раз заходит на какой-то сайт у него сразу есть логин и пароль?
У юзера по умолчанию есть отрицательное значение авторизации (`session: false`) и только когда он регистрируется, появляется логин и пароль

2023-03-23 07:12 UTC, oksssvv commented on authorizaion.ts
> +  session?: boolean
> Почему ты пишешь, что у тебя все 3 обязательных свойства? Если в коде не так. Что означает знак вопроса перед двоеточием?
я аргументировала обязательность используемых типов, а свойств - упустила

Ошибку поняла - исправлю

2023-03-23 09:16 UTC, eshevlyakova reviewed
Также не выполнено [условие](https://github.com/atls-academy/oksssvv.github.io/issues/3#:~:text=%D0%94%D0%BE%D0%BB%D0%B6%D0%BD%D0%B0%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D1%8C%20%D0%BA%D1%80%D0%B5%D0%B4%D1%8B%20(credentials)%20%D0%B4%D0%BB%D1%8F%20%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9)

2023-03-23 09:16 UTC, eshevlyakova commented on authorizaion.ts
> +    } else throw error[5]
Убери глубокую вложенность во всех функциях

2023-03-23 09:16 UTC, eshevlyakova commented on authorizaion.ts
> +  } catch (Error) {
Ты в catch передаешь ошибку но не используешь ее. Также помимо return выводи еще в консоль ошибку и результаты функций, чтобы наглядно было видно, какие операции произошли и их статус

2023-03-24 07:41 UTC, oksssvv commented on authorizaion.ts
> +  } catch (Error) {
@eshevlyakova 
>Ты в catch передаешь ошибку но не используешь ее.

Убрала круглые скобки с ошибкой в поле catch

> Также помимо return выводи еще в консоль ошибку и результаты функций

т.е. в поле catch возвращать console.log() и переменную user?

2023-03-24 07:48 UTC, eshevlyakova commented on authorizaion.ts
> +  } catch (Error) {
@oksssvv 
> Убрала круглые скобки с ошибкой в поле catch

Зачем? В блоке try ты должна генерировать ошибки и потом в catch выбрасывать их. Посмотри это: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

> т.е. в поле catch возвращать console.log() и переменную user?

Для чего используется блок catch и в каких случаях оно выполняется?

2023-03-24 11:49 UTC, oksssvv commented on authorizaion.ts
> +  } catch (Error) {
@eshevlyakova 
- Убрала глубокую вложенность
- Поместила ошибку в круглые скобки в поле `catch`
- Вернула ошибку в теле `catch` при помощи return 

Не совсем поняла что именно подразумевается под выводом результата функции, то, что пользователь ввел верно?
т.е. если одно из поставленных условий не выполняется поле `catch` - выводит:
 1. Какая ошибка совершена 
 2. Какие данные были указаны верно 
 Правильно понимаю?

2023-03-24 11:54 UTC, eshevlyakova commented on authorizaion.ts
> +  } catch (Error) {
@oksssvv 
> Не совсем поняла что именно подразумевается под выводом результата функции, то, что пользователь ввел верно?

Результат функции это точно не то, что ввел пользователь). Например результатом функции регистрации будет регистрация, значит выводи в консоль, что юзер зарегистрирован

> т.е. если одно из поставленных условий не выполняется поле catch - выводит:
>
>Какая ошибка совершена
>Какие данные были указаны верно

Это не поняла, напиши подробнее

2023-03-24 12:05 UTC, oksssvv commented on authorizaion.ts
> +  } catch (Error) {
@eshevlyakova 

- Сейчас  функция при вводе правильных параметров возвращает строку об успешной регистрации, и записывает эти данные в переменную user

- В противном случае поле `catch` возвращает совершенную ошибку и строку 'registration failed'

**Вопрос**
`catch` еще что то должен возвращать?

2023-03-24 12:09 UTC, eshevlyakova commented on authorizaion.ts
> +  } catch (Error) {
@oksssvv 
> возвращает совершенную ошибку и строку 'registration failed'

Только это можно сделать в одной строке. Сначала пиши что регистрация не прошла и с помощью шаблонных строке выводи ошибку (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals)

> catch еще что то должен возвращать?

Нет

2023-03-24 12:17 UTC, oksssvv commented on authorizaion.ts
> +  } catch (Error) {
@eshevlyakova 
Спасибо, сейчас выложу функцию регистрации для ревью

2023-03-24 12:18 UTC, eshevlyakova commented on authorizaion.ts
> +  } catch (Error) {
@oksssvv 
> Спасибо, сейчас выложу функцию регистрации для ревью

запрашуй ревью, когда выполнишь все условия задания

2023-03-24 13:01 UTC, oksssvv commented
@eshevlyakova 

> Также не выполнено [условие](https://github.com/atls-academy/oksssvv.github.io/issues/3#:~:text=%D0%94%D0%BE%D0%BB%D0%B6%D0%BD%D0%B0%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D1%8C%20%D0%BA%D1%80%D0%B5%D0%B4%D1%8B%20(credentials)%20%D0%B4%D0%BB%D1%8F%20%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9)

**Вопрос**
`credentials` нужно осуществить как отдельную функцию или их возможно поместить в функцию регистрации?

(не нахожу в интернете инфы как это вопротить)

2023-03-24 13:10 UTC, eshevlyakova commented
@oksssvv 
> credentials нужно осуществить как отдельную функцию или их возможно поместить в функцию регистрации?

Во первых credentials - это не функция, а массив данных пользователя. Следовательно пушить данные в этот массив нужно в момент регистрации или входа, и это можно сделать в этих же функциях

2023-03-24 14:09 UTC, oksssvv commented
@eshevlyakova 

> Во первых credentials - это не функция, а массив данных пользователя. Следовательно пушить данные в этот массив нужно в момент регистрации или входа, и это можно сделать в этих же функциях

- т.е. при регистрации запись данных идет в `credentials`, а не в переменную `user`?

- а в `user` данные (имя, пароль, изменение сессии на true) записываются когда совершается `login`?

2023-03-24 14:11 UTC, eshevlyakova commented
@oksssvv 

1. Нет
2. Нет

Почитай что такое креды

2023-03-24 14:24 UTC, oksssvv commented
@eshevlyakova 
В таком случае - я создала массив в который пушится массив состоящий из 2х строк: имя и пароль, когда регистрация данного пользователя прошла успешно

2023-03-24 14:56 UTC, eshevlyakova commented on authorizaion.ts
> +      throw new Error(`User with login ${name} not found`)
Во первых у тебя есть база данных в которую ты записываешь data всех пользователей? А во вторых скинь ссылку на этот пункт задания

2023-03-24 14:56 UTC, eshevlyakova commented on authorizaion.ts
> +    return `${user.username} session is currently active`
В задании просят вывести в консоль, и в целом для всех функция добавь (удобно для откладки)

2023-03-24 15:00 UTC, oxiqod commented on authorizaion.ts
> +      throw new Error(`User with login ${name} not found`)
@eshevlyakova 
Поняла, сейчас уберу

2023-03-24 15:04 UTC, eshevlyakova commented on authorizaion.ts
> +    return `${user.username} session is currently active`
Зачем ты отредактировала мое сообщение?) На первой строке напиши это `/* eslint no-console: 0 */` 
Если интересно можешь быстро взглянуть на эту статью https://eslint.org/docs/latest/rules/no-console

2023-03-24 15:05 UTC, oksssvv commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@eshevlyakova 

>В задании просят вывести в консоль, и в целом для всех функция добавь (удобно для откладки)

но `lint` ругается на `console.log()`

2023-03-24 15:17 UTC, oksssvv commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@eshevlyakova 

Уточню во избежании множества пушев:
- я во всех функциях после `return` возвращаемую строку заношу в `console.log()`
- а также во всех функциях возвращаемый тип изменяю на - `string | void` ?

2023-03-24 15:31 UTC, eshevlyakova commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@oksssvv 
> я во всех функциях после return возвращаемую строку заношу в console.log()

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/return

> а также во всех функциях возвращаемый тип изменяю на - string | void ?

Аргументируй почему именно так и почему вообще решила изменять тип возвращаемых данных? console.log возвращает что-то из функции?

2023-03-24 15:39 UTC, oksssvv commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@eshevlyakova 
Я тебя недопоняла, сам вызов функции поместить в `console.log()` ты имела ввиду?

2023-03-24 15:44 UTC, eshevlyakova commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@oksssvv 

> сам вызов функции поместить в console.log() ты имела ввиду?

Нет. После return никакой код не выполняется, на [первой строчке написано](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/return#:~:text=%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B0%D0%B5%D1%82%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B9%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8)

2023-03-24 15:52 UTC, oksssvv commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@eshevlyakova 
Нет. Я имела ввиду вывести в консоль последующий вызов функции?, т.е:
 `console.log( register('Admin','101010') )`
 `console.log( login('Admin','101010') )`
 `console.log( whoami() )`
 
 если ты не об этом, то скажи поподробнее

2023-03-24 15:56 UTC, eshevlyakova commented on authorizaion.ts
> +    return `${user.username} session is currently active`
@oksssvv 

>> после return возвращаемую строку заношу в console.log()

> я понимаю что в функции после return - ничего не выводится

у тебя есть [условие в задании](https://github.com/atls-academy/oksssvv.github.io/issues/3#:~:text=%D0%B2%20%D0%BA%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D0%B8%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4) — сделай его, если есть какие-то точные вопросы, то спрашивай

2023-03-24 16:24 UTC, eshevlyakova commented on authorizaion.ts
> +    if (user.username !== name && user.password !== pass) throw new Error(`User not found`)
Уже писала об этой ошибке

2023-03-24 16:24 UTC, eshevlyakova commented on authorizaion.ts
> +    console.log(`${name}`, `${pass}`, credentials)
В консоль выводи те же сообщения, что и в return. Это просто для удобство, чтобы следить какое действие произошло потому что return в консоли никак не отображаются

2023-03-24 16:24 UTC, eshevlyakova commented on authorizaion.ts
> +    return `Registration failed. ${Error}`
Ошибки тоже выводи в консоль

2023-03-25 08:22 UTC, eshevlyakova commented on oksssvv.github.io
Что это такое?

2023-03-25 08:22 UTC, eshevlyakova commented on authorizaion.ts
> +const credentials: [string[]?] = []
Ты можешь сразу пушить сюда объект пользователя, а не отдельные данные

2023-03-25 08:22 UTC, eshevlyakova commented on authorizaion.ts
> +const login = (name: string, pass: string): string => {
При входе креды тоже нужно запоминать

2023-03-25 08:22 UTC, eshevlyakova commented on authorizaion.ts
> +    user.session = true
Почему ты изменяешь только состояние входа, но не запоминаешь данные пользователя?

2023-03-25 08:22 UTC, eshevlyakova commented on authorizaion.ts
> +    if (user.username !== name && user.password !== pass) throw new Error(`User not registered`)
Я тебе третий раз пишу про это. Где в условиях задания написано отлавливать эту ошибку? И как ты ее вообще отлавливаешь если нет базы данных?
Попробуй вводить разные логины и пароли и твой код сломается

2023-03-25 09:30 UTC, oksssvv commented on authorizaion.ts
> +    user.session = true
>Почему ты изменяешь только состояние входа, но не запоминаешь данные пользователя?

но они записываются в функции `register` в переменную `user`, и на момент `login'a` остается только изменить булевое значение сессии

Получается что эта конструкция работает некорректно?

2023-03-25 09:33 UTC, oksssvv commented on authorizaion.ts
> +    user.session = true
надо при регистрации записывать данные в креды, а затем при логине сверять это имя и пароль в кредах,  и при верных вводных пушить в переменную `user`, получается?

2023-03-25 09:34 UTC, eshevlyakova commented on authorizaion.ts
> +    user.session = true
@oksssvv 

> но они записываются в функции register в переменную user, и на момент login'a остается только изменить булевое значение сессии

В задании нет этого пункта, что нельзя войти в "аккаунт" если ты до этого не зарегался. Логически это странно, но у тебя есть пункты задания

> Получается что эта конструкция работает некорректно?

Да

2023-03-25 09:39 UTC, oksssvv commented on authorizaion.ts
> +    user.session = true
т.е. эта строка вообще не имеет значения и её можно вырезать?

[строка кода](https://github.com/atls-academy/oksssvv.github.io/pull/7/commits/cb17a39b698a84e42202d0ff73480b41841ab382#diff-a3f485405c8ff9c9de1a9340ca251591e702a15a14ff9fde37b26840283f671dR31)

2023-03-25 09:40 UTC, oksssvv commented on authorizaion.ts
> +    user.session = true
@eshevlyakova 
т.е. эта строка вообще не имеет значения и её можно вырезать?

[строка кода](https://github.com/atls-academy/oksssvv.github.io/pull/7/commits/cb17a39b698a84e42202d0ff73480b41841ab382#diff-a3f485405c8ff9c9de1a9340ca251591e702a15a14ff9fde37b26840283f671dR31)

2023-03-25 09:43 UTC, oksssvv commented on authorizaion.ts
> +    user.session = true
нет не можно, поняла , логин просто перезапишет данные при регистрации

2023-03-25 14:28 UTC, eshevlyakova commented on oksssvv.github.io
Убери это

2023-03-25 14:45 UTC, oksssvv commented on oksssvv.github.io
>Убери это

что? ты уже второй раз пишешь, а у меня - ничего

**медиа**
![a](https://user-images.githubusercontent.com/126156026/227724289-3fbb17cb-a39f-4a46-894b-76c8460b222f.png)

2023-03-25 14:49 UTC, eshevlyakova commented on oksssvv.github.io
@oksssvv 

1. Если не поняла, что нужно убрать, то нужно написать об этом
2. У тебя все отображается, посмотри на название файла, что это такое? и убирай
<img width="965" alt="Снимок экрана 2023-03-25 в 17 48 34" src="https://user-images.githubusercontent.com/79781486/227724520-637b38a0-21ed-413a-9e8d-80e390bcde8c.png">

2023-03-25 15:13 UTC, oksssvv commented on oksssvv.github.io
>У тебя все отображается, посмотри на название файла/папки, что это такое? и убирай

локально убрала, что б здесь изменить - нужно запушить без этой папки?

2023-03-25 15:23 UTC, eshevlyakova commented on oksssvv.github.io
@oksssvv 

> локально убрала, что б здесь изменить - нужно запушить без этой папки?

ты сделала локальные изменения, все как обычно. Коммит и пуш

2023-03-25 16:21 UTC, eshevlyakova commented on authorizaion.ts
> +const register = (name: string, pass: string): string => {
При регистрации мы также остаемся в аккаунте, то есть сессия активна

2023-03-25 16:21 UTC, eshevlyakova commented on authorizaion.ts
> +const user: User = { session: false }
Константа не меняет своего значения, а ты изменяешь/добавляешь свойства

2023-03-26 07:05 UTC, oksssvv commented
@eshevlyakova 
>Константа не меняет своего значения, а ты изменяешь/добавляешь свойства

`lint` ругается если поменять на `let`, ведь переменная всегда имеет свойство `session`, и при использовании дальнейших функций меняются только свойства в её теле

2023-03-26 07:06 UTC, eshevlyakova commented
@oksssvv 

> lint ругается если поменять на let, ведь переменная всегда имеет свойство session, и при использовании дальнейших функций меняются только свойства в её теле

Да все верно, оставляй так

2023-03-26 07:12 UTC, oksssvv commented
@eshevlyakova 

Только сейчас увидела что можно убрать `else` в функции `logout`, перепушить?

2023-03-26 07:21 UTC, eshevlyakova commented
@oksssvv 
> Только сейчас увидела что можно убрать else в функции logout, перепушить?

Правильно, что добавила контекст. И да можешь убрать

2023-03-26 07:32 UTC, oksssvv commented
@eshevlyakova 
нет кнопки запросить ревью, уже ожидается

2023-03-26 07:35 UTC, eshevlyakova approved these changes

2023-03-26 22:38 UTC, TorinAsakura requested changes
Что я точно не пропущу:
- использование try в данном случае не имеет смысла так как у тебя внутри уже три условия
- опечатка в названии модуля
- нарушение стайлгайдов typescript
- нарушение доменной модели - модуль авторизации содержит в себе сразу ВСЁ, в реальности такого не может быть

Материалы для повышения общего уровня грамотности:
- https://habr.com/ru/post/21376/
- https://google.github.io/styleguide/tsguide.html

2023-03-27 06:17 UTC, oksssvv commented
@eshevlyakova 
**Вопрос**
мне убирать все конструкции try...catch, а следовательно инструкции throw?

2023-03-27 06:31 UTC, eshevlyakova commented
@oksssvv 

> мне убирать все конструкции try...catch, а следовательно инструкции throw?

Нет, ты просто убираешь конструкцию  try...catch, а ошибки также генерируешь, когда выполняются if

2023-03-28 08:09 UTC, oksssvv commented
@eshevlyakova 

**Скоуп**
Соблюдение доменной модели

**Вопрос**
Необходимо вынести в другой файл сущности: интерфейс `User`, переменную `user` и переменную `credentials`?

**Контекст**
[строки кода](https://github.com/atls-academy/oksssvv.github.io/pull/7/commits/3a5633a9d6cee2c77a8bb2911ff7ff44b2c6d0bb#diff-a3f485405c8ff9c9de1a9340ca251591e702a15a14ff9fde37b26840283f671dR2-R10)

2023-03-28 08:20 UTC, eshevlyakova commented
@oksssvv 

> Необходимо вынести в другой файл сущности: интерфейс User, переменную user и переменную credentials?

Наоборот, необходимо вынести интерфейсы и функции (регистрация, входа и тд) в разные папки/файлы и импортировать в основной файл

2023-03-28 12:09 UTC, eshevlyakova commented on authorization/functions.ts
Под каждую функцию свой файл

2023-03-28 12:09 UTC, eshevlyakova commented on authorization/functions.ts
> +import { credentials } from './index'
Не импортируй переменные, а указывай их в аргументах функции и передавай

2023-03-28 15:53 UTC, oksssvv commented
@eshevlyakova

>Не импортируй переменные, а указывай их в аргументах функции и передавай

При передаче аргумента - линт начинает ругаться присвоение свойства параметру функции, т.е. не дает присваивать переменной user имена, пароли и тд.

2023-03-28 16:12 UTC, oksssvv commented
@eshevlyakova

**Скоуп**
изменение свойств пользователя

**Описание**
проверка `lint` выбрасывает ошибку при попытке изменить свойства параметра передаваемого в функцию, аргументом которого является переменная `user`

**Воспроизведение**
1. Добавляю параметр в функцию
2. Передаю в функцию как аргумент переменную `user`
3. Проверка `lint` выдает ошибку 

**Логи** 
`
➤ YN0000: │   Error: Assignment to property of function parameter 'user0'. no-param-reassign
➤ YN0000: │ 
➤ YN0000: │    7 |   user0.userName = name
➤ YN0000: │    8 |   user0.password = pass
➤ YN0000: │ >  9 |   user0.session = true
➤ YN0000: │      |   ^
➤ YN0000: │   10 |   cred.push(user0)
➤ YN0000: │   11 |   console.log(`You have successfully login as ${name}.`)
➤ YN0000: │   12 |   return `You have successfully login as ${name}.`
➤ YN0000: │ 
➤ YN0000: │ authorization/logout.ts:7:3
➤ YN0000: │ 
➤ YN0000: │   Error: Assignment to property of function parameter 'user0'. no-param-reassign
➤ YN0000: │ 
➤ YN0000: │    5 | const logout = (user0: User): string => {
➤ YN0000: │    6 |   if (user0.session !== true) throw new Error('There is currently no active session.')
➤ YN0000: │ >  7 |   user0.session = false
➤ YN0000: │      |   ^
➤ YN0000: │    8 |   console.log(`You have successfully logout of ${user0.userName} session.`)
➤ YN0000: │    9 |   return `You have successfully logout of ${user0.userName} session.`
➤ YN0000: │   10 | }
➤ YN0000: │ 
➤ YN0000: │ authorization/register.ts:9:3
➤ YN0000: │ 
➤ YN0000: │   Error: Assignment to property of function parameter 'user0'. no-param-reassign
➤ YN0000: │ 
➤ YN0000: │    7 |   if (name.length < 5) throw new Error('Name must be at least 5 characters.')
➤ YN0000: │    8 |   if (pass.length < 6) throw new Error('Password must be at least 6.')
➤ YN0000: │ >  9 |   user0.userName = name
➤ YN0000: │      |   ^
➤ YN0000: │   10 |   user0.password = pass
➤ YN0000: │   11 |   user0.session = true
➤ YN0000: │   12 |   cred.push(user0)
➤ YN0000: │ 
➤ YN0000: │ authorization/register.ts:10:3
➤ YN0000: │ 
➤ YN0000: │   Error: Assignment to property of function parameter 'user0'. no-param-reassign
➤ YN0000: │ 
➤ YN0000: │    8 |   if (pass.length < 6) throw new Error('Password must be at least 6.')
➤ YN0000: │    9 |   user0.userName = name
➤ YN0000: │ > 10 |   user0.password = pass
➤ YN0000: │      |   ^
➤ YN0000: │   11 |   user0.session = true
➤ YN0000: │   12 |   cred.push(user0)
➤ YN0000: │   13 |   console.log(`Registration of user ${name} was successful.`)
`

**Вопрос**
Каким способом валидно изменять переменную через передачу в функцию как аргумент?

2023-03-28 16:41 UTC, eshevlyakova commented
@oksssvv 

> Каким способом валидно изменять переменную через передачу в функцию как аргумент?

В начале файла добавь это: `/* eslint-disable no-param-reassign */ `

И почему user0 в качестве аргумента? Сделай просто user

2023-03-29 04:16 UTC, eshevlyakova commented on authorization/logout.ts
> +  user.session = false
Используй везде не присвоение значения определенному свойству, а присвоение объекта. Пример:
```typescript
user = {
  session: false
}
```

 Потому что в данном случае сессия не активна, но при этом пароль и логин сохраняются, так как ты переопределила только одно свойство, а не объект

2023-03-29 06:27 UTC, oksssvv commented
@eshevlyakova

>Используй везде не присвоение значения определенному свойству, а присвоение объекта.

**Воспроизведение**

1. в функции register я присваиваю переменной user объект со всеми нужными свойствами(имя, пароль, сессия)
2. в консоль есть вывод об успешной регистрации
3. проверяю через вывод в консоль переменную user - а там ничего не изменилось ( т.е. { session: false} )

как я поняла это присваивание не вышло за пределы функции. оригинальный объект не поменялся, затем я попробовала сделать тип переменной user - let - всё равно ничего

при этом в креды всё пушится исправно

2023-03-29 08:50 UTC, oksssvv commented
@eshevlyakova 

**Скоуп**
выход из сессии 

**Описание**
При вызове функции `logout` в переменной `user` остаются данные о пользователе (`userName` и `password`)
 
**Контекст**
[Функция `logout`](https://github.com/atls-academy/oksssvv.github.io/pull/7/commits/5982a3d1ece3709917a6219c3d6725e3ac55dfc5#diff-33d60c1b0616183cad100f5d2cd2de51da0bcf338566d18ea7b6ffaa39d15ebfR6-R10)

**Вопрос**
Как осуществить корректно 'обнуление' свойств `userName` и `password` при помощи функции `logout`?

2023-03-29 09:16 UTC, eshevlyakova commented
@oksssvv 

> Как осуществить корректно 'обнуление' свойств userName и password при помощи функции logout?

Чтобы удалить свойство объекта через мутацию можно использовать оператор delete

2023-03-29 09:25 UTC, oksssvv commented
@eshevlyakova 

**Вопрос**
Тестовые вызовы функций могут находиться в файле с переменной `user`?

**Контекст**
[строки кода](https://github.com/atls-academy/oksssvv.github.io/pull/7/files#diff-b7c322d9fa6cb146d38c4ebb82d051b5c0d212feec68ec1d63c660fd0cb3f360R11-R15)

2023-03-29 09:33 UTC, eshevlyakova commented
@oksssvv 

> Тестовые вызовы функций могут находиться в файле с переменной user?

Да, а почему не могут?

2023-03-29 09:46 UTC, eshevlyakova approved these changes

2023-03-29 09:46 UTC, eshevlyakova commented on authorization/index.ts
> +export { user, credentials }
Куда ты их экспортируешь?

2023-03-30 08:27 UTC, TorinAsakura commented on authorization/index.ts
> +// test
если пытаешься писать тест - пиши его в отдельном модуле

твои фичи должны собираться словно это конструктор

это опционально конечно же, но, на будущее запомни

пример https://github.com/atls/serenity/blob/dev/collaboration/ee2/src/reply.spec.ts

2023-03-30 08:30 UTC, TorinAsakura commented on authorization/interface.ts
> +interface User {
поправь нейминг файлов

паттерн примерно такой entity.interface.ts

в твоём случае entity - authorization

кстати, authorization разрешается писать как auth - общепринятое, конвенциональное сокращение

2023-03-30 08:37 UTC, TorinAsakura requested changes

2023-03-30 08:37 UTC, TorinAsakura commented on authorization/login.ts
> +const login = (user: User, cred: User[], name: string, pass: string): string => {
это точно должна быть функция

2023-03-30 08:37 UTC, TorinAsakura commented on authorization/login.ts
> +  user.session = true
это должно быть аргументами передаваемыми в функцию

если ты будешь так писать код - у тебя ничего по итогу не будет работать

2023-03-30 08:37 UTC, TorinAsakura commented on authorization/login.ts
> +  console.log(`You have successfully login as ${name}.`)
Если ты готовишь свой ПР к слиянию - в нём не должно быть отладочной информаци

2023-03-30 08:37 UTC, TorinAsakura commented on authorization/logout.ts
> +const logout = (user: User): string => {
https://github.com/atls/project-starter/tree/master/identity/pages/logout-page/src пример как должны быть описаны твои события имеющие эффекты

пока используем только TypeScript, никаких сторонних либ

Я хочу чтобы ты поняла философию чистого кода

2023-03-31 06:56 UTC, oksssvv commented
@eshevlyakova 

> это должно быть аргументами передаваемыми в функцию
> если ты будешь так писать код - у тебя ничего по итогу не будет работать

[строки кода](https://github.com/atls-academy/oksssvv.github.io/pull/7/files/df8b2b98b4085b2fb3f6ace7c7dbee585207a5e4#diff-445467884e3a07179e6e2de85b9d8a6144ee80d76e9c96bcea09cfdaf7f05486R8-R10)

**Описание**
Пробовала в функции присваивать переменной `user` объект с соответствующими свойствами - не работает
Пробовала передавать в функцию как аргументы отдельные свойства переменной `user` - тоже не работает

**Вопрос**
Как правильно изменять свойства объекта `user` в функциях?

2023-03-31 07:02 UTC, eshevlyakova commented
@oksssvv 

> Пробовала передавать в функцию как аргументы отдельные свойства переменной user

Пришли ссылку на код, как ты это реализовала

2023-03-31 07:18 UTC, oksssvv commented
@eshevlyakova 
```typescript  

const register = (userName: undefined | string,password: undefined | string, session: boolean, cred: User[], name: string, pass: string): string => {
  if (user.session === true) throw new Error('There is already an active session at the moment.');
  if (name.length < 5) throw new Error('Name must be at least 5 characters.');
  if (pass.length < 6) throw new Error('Password must be at least 6.');
  userName = name
  password = pass
  session = true
  cred.push(user);
  console.log(`Registration of user ${name} was successful.`);
  return `Registration of user ${name} was successful.`;
}

register(user.userName,user.password, user.session,credentials,'Admin','101010')


```

2023-03-31 08:45 UTC, TorinAsakura approved these changes

2023-03-31 08:45 UTC, merged